export type FruitTier = 'S' | 'A' | 'B' | 'C' | 'D';
export type FruitType = 'Natural' | 'Elemental' | 'Beast';

export interface Fruit {
  id: string;
  name: string;
  emoji: string;
  tier: FruitTier;
  type: FruitType;
  value: number; // in Robux equivalent
  demand: number; // 1-10
  rarity: 'Common' | 'Uncommon' | 'Rare' | 'Legendary' | 'Mythical';
  pvpRating: number; // 1-10
  pveRating: number; // 1-10
  mobility: number; // 1-10
  price: number; // in-game Beli
  description: string;
  trending?: 'up' | 'down' | 'stable';
}

export const fruits: Fruit[] = [
  // S TIER
  {
    id: 'dragon',
    name: 'Dragon',
    emoji: '🐉',
    tier: 'S',
    type: 'Beast',
    value: 35000,
    demand: 10,
    rarity: 'Mythical',
    pvpRating: 10,
    pveRating: 9,
    mobility: 10,
    price: 3500000,
    description: 'The most powerful fruit in the game. Transforms into a dragon with devastating AoE attacks and unmatched mobility.',
    trending: 'stable',
  },
  {
    id: 'leopard',
    name: 'Leopard',
    emoji: '🐆',
    tier: 'S',
    type: 'Beast',
    value: 38000,
    demand: 10,
    rarity: 'Mythical',
    pvpRating: 10,
    pveRating: 8,
    mobility: 10,
    price: 5000000,
    description: 'The highest PVP potential in the game. Insane speed and burst damage make it the #1 competitive fruit.',
    trending: 'up',
  },
  {
    id: 'venom',
    name: 'Venom',
    emoji: '☠️',
    tier: 'S',
    type: 'Natural',
    value: 28000,
    demand: 9,
    rarity: 'Mythical',
    pvpRating: 9,
    pveRating: 10,
    mobility: 7,
    price: 3000000,
    description: 'Corrosive pools deal massive sustained damage. Top-tier for boss fights and grinding with excellent range.',
    trending: 'stable',
  },
  {
    id: 'shadow',
    name: 'Shadow',
    emoji: '🌑',
    tier: 'S',
    type: 'Natural',
    value: 25000,
    demand: 9,
    rarity: 'Legendary',
    pvpRating: 9,
    pveRating: 8,
    mobility: 9,
    price: 2900000,
    description: 'Powerful dark attacks with Zombie awakening. One of the best fruits for both PVP and PVE.',
    trending: 'up',
  },
  {
    id: 'dough',
    name: 'Dough',
    emoji: '🍩',
    tier: 'S',
    type: 'Elemental',
    value: 24000,
    demand: 9,
    rarity: 'Legendary',
    pvpRating: 9,
    pveRating: 8,
    mobility: 8,
    price: 2800000,
    description: 'Extremely sticky and hard to escape. Massive damage and good hitboxes make it a fan favourite in PVP.',
    trending: 'stable',
  },
  // A TIER
  {
    id: 'blizzard',
    name: 'Blizzard',
    emoji: '❄️',
    tier: 'A',
    type: 'Natural',
    value: 18000,
    demand: 8,
    rarity: 'Legendary',
    pvpRating: 8,
    pveRating: 8,
    mobility: 8,
    price: 2400000,
    description: 'Freezing AoE attacks and excellent range. Strong all-rounder for PVP and grinding.',
    trending: 'up',
  },
  {
    id: 'phoenix',
    name: 'Phoenix',
    emoji: '🔥',
    tier: 'A',
    type: 'Beast',
    value: 16000,
    demand: 8,
    rarity: 'Legendary',
    pvpRating: 7,
    pveRating: 10,
    mobility: 9,
    price: 1800000,
    description: 'Healing capabilities make it the best support and grinding fruit. Transforms into a firebird for insane sustain.',
    trending: 'stable',
  },
  {
    id: 'lightning',
    name: 'Lightning',
    emoji: '⚡',
    tier: 'A',
    type: 'Elemental',
    value: 14000,
    demand: 7,
    rarity: 'Rare',
    pvpRating: 8,
    pveRating: 7,
    mobility: 10,
    price: 1400000,
    description: 'Fastest travel speed in the game. Great for hit-and-run PVP tactics.',
    trending: 'stable',
  },
  {
    id: 'magma',
    name: 'Magma',
    emoji: '🌋',
    tier: 'A',
    type: 'Elemental',
    value: 13000,
    demand: 7,
    rarity: 'Rare',
    pvpRating: 7,
    pveRating: 9,
    mobility: 6,
    price: 850000,
    description: 'Highest raw damage output against bosses. Lava floor control and burning damage over time.',
    trending: 'down',
  },
  {
    id: 'gravity',
    name: 'Gravity',
    emoji: '👻',
    tier: 'A',
    type: 'Natural',
    value: 15000,
    demand: 8,
    rarity: 'Legendary',
    pvpRating: 8,
    pveRating: 7,
    mobility: 7,
    price: 2500000,
    description: 'Unique gravity manipulation. Can knock enemies into the air and stack massive damage.',
    trending: 'up',
  },
  {
    id: 'control',
    name: 'Control',
    emoji: '🎮',
    tier: 'A',
    type: 'Natural',
    value: 20000,
    demand: 9,
    rarity: 'Mythical',
    pvpRating: 9,
    pveRating: 7,
    mobility: 8,
    price: 3000000,
    description: 'Incredible PVP utility with teleportation and portal creation. Hard to master but very rewarding.',
    trending: 'up',
  },
  // B TIER
  {
    id: 'ice',
    name: 'Ice',
    emoji: '🧊',
    tier: 'B',
    type: 'Elemental',
    value: 9000,
    demand: 6,
    rarity: 'Uncommon',
    pvpRating: 6,
    pveRating: 7,
    mobility: 7,
    price: 350000,
    description: 'Reliable freeze CC and solid damage. Great starter fruit for Sea 2.',
    trending: 'stable',
  },
  {
    id: 'dark',
    name: 'Dark',
    emoji: '🌚',
    tier: 'B',
    type: 'Elemental',
    value: 8000,
    demand: 6,
    rarity: 'Uncommon',
    pvpRating: 7,
    pveRating: 6,
    mobility: 6,
    price: 500000,
    description: 'Good range and dark vortex pull mechanics. Solid PVP option for mid-tier players.',
    trending: 'stable',
  },
  {
    id: 'light',
    name: 'Light',
    emoji: '💡',
    tier: 'B',
    type: 'Elemental',
    value: 10000,
    demand: 7,
    rarity: 'Rare',
    pvpRating: 7,
    pveRating: 7,
    mobility: 10,
    price: 650000,
    description: 'Fastest projectile speed and excellent mobility. Good for long-range combat.',
    trending: 'stable',
  },
  {
    id: 'spider',
    name: 'Spider',
    emoji: '🕸️',
    tier: 'B',
    type: 'Natural',
    value: 8500,
    demand: 6,
    rarity: 'Uncommon',
    pvpRating: 6,
    pveRating: 6,
    mobility: 7,
    price: 1500000,
    description: 'Web traps and area denial. Unique mechanics for creative PVP players.',
    trending: 'down',
  },
  {
    id: 'buddha',
    name: 'Buddha',
    emoji: '🗿',
    tier: 'B',
    type: 'Beast',
    value: 11000,
    demand: 7,
    rarity: 'Rare',
    pvpRating: 6,
    pveRating: 9,
    mobility: 5,
    price: 1200000,
    description: 'Massive hitbox in transformed state. The best fruit for sword users and grinding mobs.',
    trending: 'stable',
  },
  // C TIER
  {
    id: 'rumble',
    name: 'Rumble',
    emoji: '⚡',
    tier: 'C',
    type: 'Natural',
    value: 5000,
    demand: 5,
    rarity: 'Uncommon',
    pvpRating: 5,
    pveRating: 5,
    mobility: 6,
    price: 2100000,
    description: 'Thunder-based attacks with decent AoE. Falls short compared to top tiers in current meta.',
    trending: 'down',
  },
  {
    id: 'quake',
    name: 'Quake',
    emoji: '🔱',
    tier: 'C',
    type: 'Natural',
    value: 4500,
    demand: 5,
    rarity: 'Uncommon',
    pvpRating: 5,
    pveRating: 6,
    mobility: 4,
    price: 1000000,
    description: 'Massive AoE shockwaves. Good damage but very slow and predictable in PVP.',
    trending: 'stable',
  },
  {
    id: 'flame',
    name: 'Flame',
    emoji: '🔥',
    tier: 'C',
    type: 'Elemental',
    value: 4000,
    demand: 4,
    rarity: 'Common',
    pvpRating: 5,
    pveRating: 5,
    mobility: 6,
    price: 250000,
    description: 'Classic fire fruit. Reliable for early/mid game but outclassed in late game content.',
    trending: 'stable',
  },
  {
    id: 'sand',
    name: 'Sand',
    emoji: '🏜️',
    tier: 'C',
    type: 'Elemental',
    value: 3500,
    demand: 4,
    rarity: 'Common',
    pvpRating: 4,
    pveRating: 5,
    mobility: 5,
    price: 420000,
    description: 'Sand manipulation with basic area denial. Outdated in the current fast meta.',
    trending: 'down',
  },
  // D TIER
  {
    id: 'chop',
    name: 'Chop',
    emoji: '🪓',
    tier: 'D',
    type: 'Natural',
    value: 500,
    demand: 1,
    rarity: 'Common',
    pvpRating: 1,
    pveRating: 2,
    mobility: 3,
    price: 30000,
    description: 'Immune to swords but extremely weak overall. Only useful as a joke or for sword immunity.',
    trending: 'stable',
  },
  {
    id: 'bomb',
    name: 'Bomb',
    emoji: '💣',
    tier: 'D',
    type: 'Natural',
    value: 400,
    demand: 1,
    rarity: 'Common',
    pvpRating: 1,
    pveRating: 1,
    mobility: 2,
    price: 5000,
    description: 'Explosion moves with very low damage and slow speed. One of the worst fruits in the game.',
    trending: 'stable',
  },
  {
    id: 'spin',
    name: 'Spin',
    emoji: '🌀',
    tier: 'D',
    type: 'Natural',
    value: 300,
    demand: 1,
    rarity: 'Common',
    pvpRating: 1,
    pveRating: 1,
    mobility: 4,
    price: 7500,
    description: 'Spinning attacks that deal minimal damage. Vastly outclassed by any other fruit option.',
    trending: 'stable',
  },
  {
    id: 'rocket',
    name: 'Rocket',
    emoji: '🚀',
    tier: 'D',
    type: 'Natural',
    value: 350,
    demand: 1,
    rarity: 'Common',
    pvpRating: 1,
    pveRating: 2,
    mobility: 5,
    price: 5000,
    description: 'Rocket-powered moves. Novel for new players but abandoned quickly for any other fruit.',
    trending: 'stable',
  },
];

export const tierColors: Record<FruitTier, { bg: string; text: string; border: string; label: string }> = {
  S: { bg: 'rgba(255,215,0,0.12)', text: '#ffd700', border: 'rgba(255,215,0,0.4)', label: 'God Tier' },
  A: { bg: 'rgba(0,245,255,0.1)', text: '#00f5ff', border: 'rgba(0,245,255,0.35)', label: 'Top Tier' },
  B: { bg: 'rgba(46,213,115,0.1)', text: '#2ed573', border: 'rgba(46,213,115,0.3)', label: 'Solid' },
  C: { bg: 'rgba(255,165,2,0.1)', text: '#ffa502', border: 'rgba(255,165,2,0.3)', label: 'Average' },
  D: { bg: 'rgba(255,71,87,0.08)', text: '#ff4757', border: 'rgba(255,71,87,0.25)', label: 'Avoid' },
};

export const rarityColors: Record<string, string> = {
  Common: '#7a96b8',
  Uncommon: '#2ed573',
  Rare: '#00f5ff',
  Legendary: '#ffd700',
  Mythical: '#ff6b9d',
};
