export interface TeamContent {
  slug: string
  founded: number
  stadium: string
  stadiumCapacity: number
  city: string
  country: string
  nickname: string
  manager: string
  website: string
  trophies: {
    label: string
    count: number
  }[]
  history: string
  recentForm: string
  keyFacts: string[]
  colors: string
  rivals: string[]
  schema: {
    foundingDate: string
    location: string
    alternateName?: string
  }
}

const TEAM_CONTENT: Record<string, TeamContent> = {
  // ── PREMIER LEAGUE ──────────────────────────────────────────────────────────
  'manchester-united': {
    slug: 'manchester-united',
    founded: 1878,
    stadium: 'Old Trafford',
    stadiumCapacity: 74310,
    city: 'Manchester',
    country: 'England',
    nickname: 'The Red Devils',
    manager: 'Rúben Amorim',
    website: 'https://www.manutd.com',
    trophies: [
      { label: 'Premier League / First Division', count: 20 },
      { label: 'UEFA Champions League', count: 3 },
      { label: 'FA Cup', count: 13 },
      { label: 'League Cup', count: 6 },
      { label: 'UEFA Europa League', count: 1 },
      { label: 'FIFA Club World Cup', count: 1 },
    ],
    history: `Manchester United Football Club was founded in 1878 as Newton Heath LYR FC by the workers of the Lancashire and Yorkshire Railway. After financial difficulties, the club was reformed in 1902 and renamed Manchester United. The club rose to prominence under Sir Matt Busby in the 1950s and '60s, winning the European Cup in 1968 as the first English club to do so — just a decade after the Munich air disaster claimed eight players' lives. The Sir Alex Ferguson era (1986–2013) remains the most successful in English football history, delivering 13 Premier League titles, 5 FA Cups, and 2 UEFA Champions League trophies. Old Trafford, known as the "Theatre of Dreams," has been the club's home since 1910 and is the largest club stadium in England.`,
    recentForm: 'Manchester United have been rebuilding under manager Rúben Amorim, focusing on a high-energy pressing system.',
    keyFacts: [
      'Most successful club in English football history by league titles (20)',
      'One of only five English clubs to have won the UEFA Champions League',
      'Old Trafford holds 74,310 fans — the largest club stadium in England',
      'The Munich air disaster of 1958 killed eight first-team players',
      'Sir Alex Ferguson managed the club for 26 years (1986–2013)',
      'George Best, Bobby Charlton, and Denis Law are known as the "Holy Trinity"',
    ],
    colors: 'Red, White and Black',
    rivals: ['Manchester City', 'Liverpool', 'Leeds United', 'Arsenal'],
    schema: { foundingDate: '1878', location: 'Manchester, England', alternateName: 'Man Utd' },
  },
  'liverpool': {
    slug: 'liverpool',
    founded: 1892,
    stadium: 'Anfield',
    stadiumCapacity: 61015,
    city: 'Liverpool',
    country: 'England',
    nickname: 'The Reds',
    manager: 'Arne Slot',
    website: 'https://www.liverpoolfc.com',
    trophies: [
      { label: 'Premier League / First Division', count: 19 },
      { label: 'UEFA Champions League', count: 6 },
      { label: 'FA Cup', count: 8 },
      { label: 'League Cup', count: 10 },
      { label: 'UEFA Europa League', count: 3 },
      { label: 'FIFA Club World Cup', count: 1 },
    ],
    history: `Liverpool FC was founded in 1892 after a dispute between Everton FC and their landlord at Anfield. Under legendary managers Bill Shankly and Bob Paisley, Liverpool became the dominant force in English and European football through the 1970s and '80s, winning four European Cups in eight years. The Hillsborough disaster of 1989, which claimed 97 lives, remains one of the most painful chapters in the club's history. After a 30-year wait, Jürgen Klopp's Liverpool finally won the Premier League title in 2020, also adding a sixth Champions League in 2019. Their anthem "You'll Never Walk Alone" is sung around the world.`,
    recentForm: 'Under Arne Slot, Liverpool continue to challenge at the top of the Premier League.',
    keyFacts: [
      'Six UEFA Champions League titles — joint most in English football',
      '"You\'ll Never Walk Alone" is one of football\'s most iconic anthems',
      'The Kop stand at Anfield is one of football\'s most famous terraces',
      'Jürgen Klopp ended the 30-year Premier League drought in 2020',
      'Bill Shankly, Bob Paisley and Kenny Dalglish are legendary former managers',
      'Steven Gerrard is the club\'s greatest modern captain',
    ],
    colors: 'Red and White',
    rivals: ['Manchester United', 'Everton', 'Manchester City'],
    schema: { foundingDate: '1892', location: 'Liverpool, England' },
  },
  'chelsea': {
    slug: 'chelsea',
    founded: 1905,
    stadium: 'Stamford Bridge',
    stadiumCapacity: 40853,
    city: 'London',
    country: 'England',
    nickname: 'The Blues',
    manager: 'Enzo Maresca',
    website: 'https://www.chelseafc.com',
    trophies: [
      { label: 'Premier League / First Division', count: 6 },
      { label: 'UEFA Champions League', count: 2 },
      { label: 'UEFA Europa League', count: 2 },
      { label: 'FA Cup', count: 9 },
      { label: 'League Cup', count: 5 },
      { label: 'FIFA Club World Cup', count: 1 },
    ],
    history: `Chelsea FC was founded in 1905 and has been based at Stamford Bridge in Fulham ever since. After decades as a mid-table club, Roman Abramovich's takeover in 2003 transformed Chelsea into a global superpower. José Mourinho's "Special One" era brought back-to-back Premier League titles in 2004/05 and 2005/06. Under Carlo Ancelotti they won the Premier League and FA Cup double in 2010, and dramatically captured the Champions League in 2012 under Roberto Di Matteo. Since the Boehner Group's takeover in 2022, Chelsea have pursued an aggressive recruitment strategy.`,
    recentForm: 'Chelsea are competing under Enzo Maresca with a young, dynamic squad.',
    keyFacts: [
      'Two UEFA Champions League titles (2012, 2021)',
      'Roman Abramovich\'s 2003 takeover began a new era of success',
      'Stamford Bridge has been their home since the club\'s founding in 1905',
      'The "Pensioners" nickname preceded "The Blues"',
      'John Terry is the most decorated captain in the club\'s history',
      'Didier Drogba scored the 2012 Champions League final equaliser',
    ],
    colors: 'Royal Blue and White',
    rivals: ['Arsenal', 'Tottenham', 'Manchester United', 'Fulham'],
    schema: { foundingDate: '1905', location: 'London, England' },
  },
  'arsenal': {
    slug: 'arsenal',
    founded: 1886,
    stadium: 'Emirates Stadium',
    stadiumCapacity: 60704,
    city: 'London',
    country: 'England',
    nickname: 'The Gunners',
    manager: 'Mikel Arteta',
    website: 'https://www.arsenal.com',
    trophies: [
      { label: 'Premier League / First Division', count: 13 },
      { label: 'FA Cup', count: 14 },
      { label: 'League Cup', count: 2 },
      { label: 'UEFA Cup Winners\' Cup', count: 1 },
    ],
    history: `Arsenal were founded in 1886 in Woolwich, south-east London, by workers at the Royal Arsenal munitions factory. The club moved north of the river to Highbury in 1913 and became a dominant force under Herbert Chapman in the 1930s. The modern era was defined by Arsène Wenger's 22-year reign (1996–2018), during which Arsenal won three Premier League titles, including the legendary 2003/04 "Invincibles" season — 38 league games unbeaten. Wenger also revolutionised English football's approach to diet, fitness, and technical play. The club moved to the 60,704-capacity Emirates Stadium in 2006.`,
    recentForm: 'Mikel Arteta has rebuilt Arsenal into genuine Premier League title contenders.',
    keyFacts: [
      'The only team in Premier League history to complete an unbeaten season (2003/04)',
      'Hold the record for most FA Cup wins — 14',
      'Arsène Wenger managed the club for 22 years (1996–2018)',
      'Thierry Henry is the club\'s all-time top scorer with 228 goals',
      'Moved from Highbury to the Emirates Stadium in 2006',
      'First London club to win the league title (1930/31)',
    ],
    colors: 'Red and White',
    rivals: ['Tottenham', 'Chelsea', 'Manchester United'],
    schema: { foundingDate: '1886', location: 'London, England', alternateName: 'The Gunners' },
  },
  'manchester-city': {
    slug: 'manchester-city',
    founded: 1880,
    stadium: 'Etihad Stadium',
    stadiumCapacity: 55017,
    city: 'Manchester',
    country: 'England',
    nickname: 'The Citizens',
    manager: 'Pep Guardiola',
    website: 'https://www.mancity.com',
    trophies: [
      { label: 'Premier League / First Division', count: 10 },
      { label: 'UEFA Champions League', count: 1 },
      { label: 'FA Cup', count: 7 },
      { label: 'League Cup', count: 8 },
      { label: 'FIFA Club World Cup', count: 1 },
    ],
    history: `Manchester City was founded in 1880 as St Mark's (West Gorton) and adopted the current name in 1894. After decades in the shadow of Manchester United, the Abu Dhabi United Group's takeover in 2008 transformed the club entirely. Under Roberto Mancini they won the Premier League in 2012 in the most dramatic fashion — Sergio Agüero's injury-time goal against QPR. Pep Guardiola's arrival in 2016 began the most successful era in the club's history, including an historic treble in 2022/23: Premier League, FA Cup, and UEFA Champions League.`,
    recentForm: 'City remain one of Europe\'s elite clubs under Pep Guardiola\'s innovative tactics.',
    keyFacts: [
      'Won the historic treble (PL, FA Cup, Champions League) in 2022/23',
      'Sheikh Mansour\'s 2008 takeover transformed the club\'s fortunes',
      'Pep Guardiola is the most successful manager in the club\'s history',
      '"Agüerooo!" — Sergio Agüero\'s 2012 title-winning goal is one of football\'s greatest moments',
      'The Etihad Stadium was built for the 2002 Commonwealth Games',
      'Erling Haaland set a Premier League record of 36 goals in a single season (2022/23)',
    ],
    colors: 'Sky Blue and White',
    rivals: ['Manchester United', 'Liverpool', 'Chelsea'],
    schema: { foundingDate: '1880', location: 'Manchester, England', alternateName: 'Man City' },
  },
  'tottenham': {
    slug: 'tottenham',
    founded: 1882,
    stadium: 'Tottenham Hotspur Stadium',
    stadiumCapacity: 62850,
    city: 'London',
    country: 'England',
    nickname: 'Spurs',
    manager: 'Ange Postecoglou',
    website: 'https://www.tottenhamhotspur.com',
    trophies: [
      { label: 'First Division', count: 2 },
      { label: 'FA Cup', count: 8 },
      { label: 'League Cup', count: 4 },
      { label: 'UEFA Cup', count: 2 },
      { label: 'UEFA Cup Winners\' Cup', count: 1 },
    ],
    history: `Tottenham Hotspur were founded in 1882 and became the first club in the 20th century to win the Double (league and FA Cup) in 1960/61. They were also the first British club to win a European trophy, lifting the Cup Winners' Cup in 1963. The club opened a spectacular new 62,850-capacity stadium in 2019, replacing the beloved White Hart Lane. Under Mauricio Pochettino they reached the Champions League final for the first time in 2019. Harry Kane is the club's all-time top scorer before his move to Bayern Munich in 2023.`,
    recentForm: 'Spurs are playing entertaining, attacking football under Ange Postecoglou.',
    keyFacts: [
      'First 20th-century club to win the league and FA Cup Double (1960/61)',
      'First British club to win a European trophy (Cup Winners\' Cup, 1963)',
      'The new Tottenham Hotspur Stadium has a capacity of 62,850',
      'Harry Kane is the club\'s all-time top scorer (266 goals)',
      'The cockerel on the badge represents the Tottenham area\'s fighting cock tradition',
      'Jimmy Greaves scored 266 goals for the club in all competitions',
    ],
    colors: 'White and Navy Blue',
    rivals: ['Arsenal', 'Chelsea', 'West Ham'],
    schema: { foundingDate: '1882', location: 'London, England', alternateName: 'Spurs' },
  },
  'aston-villa': {
    slug: 'aston-villa',
    founded: 1874,
    stadium: 'Villa Park',
    stadiumCapacity: 42785,
    city: 'Birmingham',
    country: 'England',
    nickname: 'The Villans',
    manager: 'Unai Emery',
    website: 'https://www.avfc.co.uk',
    trophies: [
      { label: 'First Division', count: 7 },
      { label: 'UEFA Champions League / European Cup', count: 1 },
      { label: 'FA Cup', count: 7 },
      { label: 'League Cup', count: 5 },
      { label: 'UEFA Super Cup', count: 1 },
    ],
    history: `Aston Villa is one of the oldest and most decorated clubs in English football, founded in 1874. They were a founding member of the Football League in 1888 and dominated early English football. Their greatest achievement came in 1982, winning the European Cup — the pinnacle of club football at the time. After years in the wilderness including relegation in 2016, Villa bounced back under Dean Smith and have since flourished under Unai Emery, qualifying for European football and becoming genuine top-six contenders.`,
    recentForm: 'Under Unai Emery, Aston Villa have become one of the Premier League\'s most exciting teams.',
    keyFacts: [
      'European Cup winners in 1982 — one of England\'s greatest achievements',
      'One of the 12 founding members of the Football League (1888)',
      'Won seven First Division titles, most recently in 1980/81',
      'Villa Park has hosted six England international matches',
      'Ollie Watkins is the current first-choice striker',
      'Unai Emery has transformed the club since his 2022 arrival',
    ],
    colors: 'Claret and Blue',
    rivals: ['Birmingham City', 'West Brom', 'Wolves'],
    schema: { foundingDate: '1874', location: 'Birmingham, England' },
  },
  'newcastle': {
    slug: 'newcastle',
    founded: 1892,
    stadium: "St. James' Park",
    stadiumCapacity: 52305,
    city: 'Newcastle upon Tyne',
    country: 'England',
    nickname: 'The Magpies',
    manager: 'Eddie Howe',
    website: 'https://www.nufc.co.uk',
    trophies: [
      { label: 'First Division', count: 4 },
      { label: 'FA Cup', count: 6 },
      { label: 'Fairs Cup', count: 1 },
    ],
    history: `Newcastle United was formed in 1892 from the merger of Newcastle East End and Newcastle West End. The club won four First Division titles and six FA Cups in the early 20th century. Alan Shearer, the Premier League's all-time top scorer with 260 goals, remains a club legend. The Saudi Arabia-led consortium's takeover in 2021 signalled a new era of ambition. Under Eddie Howe, Newcastle qualified for the Champions League for the first time in 20 years in 2023.`,
    recentForm: 'Newcastle are pushing for European football under Eddie Howe\'s management.',
    keyFacts: [
      'Alan Shearer is the Premier League\'s all-time top scorer (260 goals)',
      'Saudi Arabia-led consortium takeover in 2021 transformed the club\'s ambitions',
      'St. James\' Park is one of England\'s largest and most atmospheric stadiums',
      'The Toon Army are renowned as some of England\'s most passionate supporters',
      'Qualified for the Champions League for the first time in 20 years in 2023',
      'Four-time First Division champions (last title 1927)',
    ],
    colors: 'Black and White',
    rivals: ['Sunderland', 'Middlesbrough'],
    schema: { foundingDate: '1892', location: 'Newcastle upon Tyne, England', alternateName: 'The Magpies' },
  },
  'west-ham': {
    slug: 'west-ham',
    founded: 1895,
    stadium: 'London Stadium',
    stadiumCapacity: 62500,
    city: 'London',
    country: 'England',
    nickname: 'The Hammers',
    manager: 'Julen Lopetegui',
    website: 'https://www.whufc.com',
    trophies: [
      { label: 'FA Cup', count: 3 },
      { label: 'UEFA Cup Winners\' Cup', count: 1 },
      { label: 'UEFA Conference League', count: 1 },
    ],
    history: `West Ham United, founded in 1895, is known as the "Academy of Football" for producing England World Cup winners Bobby Moore, Geoff Hurst and Martin Peters. The club is deeply rooted in East London working-class culture. After 112 years at Upton Park, the club moved to the London Stadium in 2016. Their greatest modern achievement came in 2023 under David Moyes, winning the UEFA Conference League — their first European trophy in 58 years.`,
    recentForm: 'West Ham are rebuilding under Julen Lopetegui following their Conference League success.',
    keyFacts: [
      'Produced three members of England\'s 1966 World Cup winning team',
      'Bobby Moore, the World Cup-winning captain, is the club\'s greatest ever player',
      'Won the UEFA Conference League in 2023 — first European trophy since 1965',
      'Known as the "Academy of Football" for their youth development',
      'Moved from Upton Park to the London Stadium in 2016',
      'The Hammers badge features two crossed riveting hammers',
    ],
    colors: 'Claret and Blue',
    rivals: ['Millwall', 'Tottenham', 'Chelsea'],
    schema: { foundingDate: '1895', location: 'London, England', alternateName: 'The Hammers' },
  },
  'everton': {
    slug: 'everton',
    founded: 1878,
    stadium: 'Goodison Park',
    stadiumCapacity: 39572,
    city: 'Liverpool',
    country: 'England',
    nickname: 'The Toffees',
    manager: 'Sean Dyche',
    website: 'https://www.evertonfc.com',
    trophies: [
      { label: 'First Division', count: 9 },
      { label: 'FA Cup', count: 5 },
      { label: 'UEFA Cup Winners\' Cup', count: 1 },
    ],
    history: `Everton Football Club, founded in 1878, is one of the founding members of the Football League and has spent more seasons in the top flight of English football than any other club. The club was the original tenant of Anfield before a boardroom dispute led to their move to Goodison Park in 1892. Their greatest era came in the 1980s under Howard Kendall, winning two league titles and the Cup Winners' Cup in 1985. A long-awaited move to a new stadium at Bramley-Moore Dock is underway.`,
    recentForm: 'Everton are fighting to establish Premier League stability under Sean Dyche.',
    keyFacts: [
      'Most seasons spent in the top division of English football',
      'One of the 12 founding members of the Football League in 1888',
      'Won the Cup Winners\' Cup in 1985 under Howard Kendall',
      'New Bramley-Moore Dock stadium is under construction',
      'The Merseyside derby against Liverpool is one of England\'s fiercest rivalries',
      'Dixie Dean\'s 60 league goals in 1927/28 is an English football record',
    ],
    colors: 'Royal Blue and White',
    rivals: ['Liverpool'],
    schema: { foundingDate: '1878', location: 'Liverpool, England', alternateName: 'The Toffees' },
  },
  'brighton': {
    slug: 'brighton',
    founded: 1901,
    stadium: 'Amex Stadium',
    stadiumCapacity: 31800,
    city: 'Brighton',
    country: 'England',
    nickname: 'The Seagulls',
    manager: 'Fabian Hürzeler',
    website: 'https://www.brightonandhovealbion.com',
    trophies: [{ label: 'FA Cup', count: 0 }],
    history: `Brighton & Hove Albion, founded in 1901, spent most of their history in the lower divisions before Tony Bloom's takeover in 2009 transformed the club. The opening of the Amex Stadium in 2011 and Bloom's data-driven approach attracted Graham Potter, then Roberto De Zerbi, both of whom turned Brighton into one of Europe's most admired footballing sides. Under De Zerbi, Brighton qualified for European football for the first time in 2023.`,
    recentForm: 'Brighton continue their innovative, possession-based football under Fabian Hürzeler.',
    keyFacts: [
      'Owner Tony Bloom is a professional poker player and football data visionary',
      'Qualified for European football for the first time in 2023',
      'Roberto De Zerbi\'s tenure produced some of the most attractive football in the league',
      'The Amex Stadium opened in 2011, ending years of nomadic existence',
      'Known for excellent youth development and data analytics',
      'Moises Caicedo was sold to Chelsea for a British transfer record £115m in 2023',
    ],
    colors: 'Blue and White',
    rivals: ['Crystal Palace'],
    schema: { foundingDate: '1901', location: 'Brighton, England', alternateName: 'The Seagulls' },
  },
  'brentford': {
    slug: 'brentford',
    founded: 1889,
    stadium: 'Gtech Community Stadium',
    stadiumCapacity: 17250,
    city: 'London',
    country: 'England',
    nickname: 'The Bees',
    manager: 'Thomas Frank',
    website: 'https://www.brentfordfc.com',
    trophies: [{ label: 'Third Division South', count: 1 }],
    history: `Brentford FC, founded in 1889, spent most of their existence in the lower divisions before a data-driven revolution under owner Matthew Benham transformed the club. Their promotion to the Premier League in 2021 — their first top-flight season since 1947 — was one of football's great fairy tales. The club moved from Griffin Park (their home for 116 years) to the new Gtech Community Stadium in 2020. Thomas Frank's reign has been marked by punching above their weight consistently.`,
    recentForm: 'Brentford continue to compete admirably in the Premier League under Thomas Frank.',
    keyFacts: [
      'First Premier League season in 74 years when promoted in 2021',
      'Owner Matthew Benham\'s data analytics company (Smartodds) drives transfers',
      'Moved from Griffin Park (116 years) to Gtech Community Stadium in 2020',
      'Ivan Toney is one of the Premier League\'s most clinical finishers',
      'Thomas Frank has been manager since 2018, one of the longest-serving in England',
      'Griffin Park was the only Football League ground with a pub on each corner',
    ],
    colors: 'Red and White',
    rivals: ['Fulham', 'QPR', 'Chelsea'],
    schema: { foundingDate: '1889', location: 'London, England', alternateName: 'The Bees' },
  },
  'wolves': {
    slug: 'wolves',
    founded: 1877,
    stadium: 'Molineux',
    stadiumCapacity: 31750,
    city: 'Wolverhampton',
    country: 'England',
    nickname: 'Wolves',
    manager: 'Vitor Pereira',
    website: 'https://www.wolves.co.uk',
    trophies: [
      { label: 'First Division', count: 3 },
      { label: 'FA Cup', count: 4 },
      { label: 'League Cup', count: 2 },
    ],
    history: `Wolverhampton Wanderers, founded in 1877, were one of England's great clubs in the 1950s under Stan Cullis, winning three First Division titles. Molineux is one of England's oldest professional grounds. After decades of decline including two relegations to the fourth tier, Fosun International's 2016 takeover and the appointment of Nuno Espírito Santo sparked a revival, culminating in promotion to the Premier League in 2018 and two consecutive seventh-place finishes.`,
    recentForm: 'Wolves are working to consolidate their Premier League status.',
    keyFacts: [
      'Three First Division titles (1954, 1958, 1959) under manager Stan Cullis',
      'Molineux is one of England\'s oldest and grandest stadiums',
      'Fosun International takeover in 2016 funded a dramatic revival',
      'Promoted from Championship in 2018 under Nuno Espírito Santo',
      'The gold and black colours are among the most distinctive in English football',
      'Billy Wright was the first footballer to earn 100 England caps',
    ],
    colors: 'Old Gold and Black',
    rivals: ['West Brom', 'Birmingham City', 'Aston Villa'],
    schema: { foundingDate: '1877', location: 'Wolverhampton, England' },
  },
  'fulham': {
    slug: 'fulham',
    founded: 1879,
    stadium: 'Craven Cottage',
    stadiumCapacity: 29600,
    city: 'London',
    country: 'England',
    nickname: 'The Cottagers',
    manager: 'Marco Silva',
    website: 'https://www.fulhamfc.com',
    trophies: [
      { label: 'Second Division', count: 2 },
      { label: 'UEFA Intertoto Cup', count: 1 },
    ],
    history: `Fulham FC, founded in 1879, is London's oldest professional football club. Their riverside ground, Craven Cottage, is one of the most charming in English football, with a unique cottage building at one corner. The club had a golden era in the early 2000s under Jean Tigana and then Roy Hodgson, finishing as runners-up in the UEFA Cup in 2010. Aleksandar Mitrović's record 43 Premier League goals in a Championship season (2021/22) powered their most recent promotion.`,
    recentForm: 'Fulham are performing well under Marco Silva in the Premier League.',
    keyFacts: [
      'London\'s oldest professional football club (founded 1879)',
      'Craven Cottage is one of English football\'s most picturesque grounds',
      'Reached the UEFA Cup final in 2010 under Roy Hodgson',
      'Aleksandar Mitrović set Championship goal record (43 goals) in 2021/22',
      'The cottage in the corner of Craven Cottage is a Grade II listed building',
      'Johnny Haynes was England\'s first £100-per-week footballer',
    ],
    colors: 'White and Black',
    rivals: ['Chelsea', 'Brentford', 'QPR'],
    schema: { foundingDate: '1879', location: 'London, England', alternateName: 'The Cottagers' },
  },
  'crystal-palace': {
    slug: 'crystal-palace',
    founded: 1905,
    stadium: 'Selhurst Park',
    stadiumCapacity: 25486,
    city: 'London',
    country: 'England',
    nickname: 'The Eagles',
    manager: 'Oliver Glasner',
    website: 'https://www.cpfc.co.uk',
    trophies: [{ label: 'Second Division', count: 1 }],
    history: `Crystal Palace, founded in 1905, play at Selhurst Park in south London. The club's most famous player, Ian Wright, went on to become Arsenal's record scorer. Palace are known for passionate supporters and the Holmesdale Road End atmosphere. Under Oliver Glasner, who arrived in 2024, Palace have rediscovered their best form. Their greatest Premier League moment was reaching the FA Cup final in 2016 under Alan Pardew, losing to Manchester United.`,
    recentForm: 'Crystal Palace have been impressive under Oliver Glasner\'s dynamic style.',
    keyFacts: [
      'Ian Wright is the club\'s all-time top scorer (117 goals)',
      'Reached the FA Cup final in 1990 and 2016',
      'Selhurst Park has one of the loudest atmospheres in English football',
      'Wilfried Zaha was a beloved figure who made 461 appearances for the club',
      'The Eagles\' nickname comes from their soaring eagle crest',
      'Oliver Glasner won the Austrian Bundesliga with LASK before moving to England',
    ],
    colors: 'Red and Blue',
    rivals: ['Brighton', 'Millwall', 'Charlton Athletic'],
    schema: { foundingDate: '1905', location: 'London, England', alternateName: 'The Eagles' },
  },
  'southampton': {
    slug: 'southampton',
    founded: 1885,
    stadium: "St. Mary's Stadium",
    stadiumCapacity: 32384,
    city: 'Southampton',
    country: 'England',
    nickname: 'The Saints',
    manager: 'Ivan Jurić',
    website: 'https://www.southamptonfc.com',
    trophies: [{ label: 'FA Cup', count: 1 }],
    history: `Southampton FC, founded in 1885 by members of St Mary's Church, have produced some of England's finest footballing talent through their renowned academy. Players like Alan Shearer, Gareth Bale, Luke Shaw and many others began their careers at Southampton. They won their only major trophy, the FA Cup, in 1976. The club moved from The Dell to St. Mary's Stadium in 2001. After relegation and promotion battles in recent years, Southampton are determined to stay in the top flight.`,
    recentForm: 'Southampton are working hard to maintain their Premier League status.',
    keyFacts: [
      'World-class academy has produced Shearer, Bale, Walcott, Lallana and many more',
      'Won the FA Cup in 1976, their only major honour',
      'Moved from The Dell (home since 1898) to St Mary\'s in 2001',
      'Matt Le Tissier, "Le God," chose loyalty to Southampton over bigger clubs',
      'Ted Bates managed the club for 18 years (1955–1973)',
      'The Saints badge features a golden halo, a reference to their church origins',
    ],
    colors: 'Red and White',
    rivals: ['Portsmouth'],
    schema: { foundingDate: '1885', location: 'Southampton, England', alternateName: 'The Saints' },
  },
  'nottingham-forest': {
    slug: 'nottingham-forest',
    founded: 1865,
    stadium: 'The City Ground',
    stadiumCapacity: 30445,
    city: 'Nottingham',
    country: 'England',
    nickname: 'The Reds',
    manager: 'Nuno Espírito Santo',
    website: 'https://www.nottinghamforest.co.uk',
    trophies: [
      { label: 'First Division', count: 1 },
      { label: 'UEFA Champions League / European Cup', count: 2 },
      { label: 'FA Cup', count: 2 },
      { label: 'League Cup', count: 4 },
    ],
    history: `Nottingham Forest, founded in 1865, achieved the extraordinary feat of winning back-to-back European Cups in 1979 and 1980 under the legendary Brian Clough — just two years after winning their first top-division title. This remarkable achievement, accomplished by a provincial club with a modest budget, remains one of English football's greatest stories. After decades in the lower divisions, Forest returned to the Premier League in 2022 under Steve Cooper, and have since established themselves back in the top flight.`,
    recentForm: 'Forest are building on their Premier League return under Nuno Espírito Santo.',
    keyFacts: [
      'Back-to-back European Cup winners in 1979 and 1980',
      'Brian Clough\'s managerial genius remains one of football\'s greatest stories',
      'One of only five English clubs to have won the European Cup / Champions League',
      'The City Ground sits beside the River Trent',
      'Stuart Pearce\'s penalty miss in the 1990 World Cup semi-final is iconic',
      'Returned to the Premier League in 2022 after 23 years away',
    ],
    colors: 'Red and White',
    rivals: ['Derby County', 'Leicester City'],
    schema: { foundingDate: '1865', location: 'Nottingham, England' },
  },
  'leicester': {
    slug: 'leicester',
    founded: 1884,
    stadium: 'King Power Stadium',
    stadiumCapacity: 32312,
    city: 'Leicester',
    country: 'England',
    nickname: 'The Foxes',
    manager: 'Steve Cooper',
    website: 'https://www.lcfc.com',
    trophies: [
      { label: 'Premier League', count: 1 },
      { label: 'FA Cup', count: 1 },
      { label: 'League Cup', count: 3 },
    ],
    history: `Leicester City's 2015/16 Premier League title win is arguably the greatest sporting upset in history. A club given 5000-1 odds of winning the title at the start of the season, led by Claudio Ranieri, defied every prediction to become champions with a squad built on teamwork, tactical discipline and Jamie Vardy's extraordinary goals. The tragic helicopter crash that killed owner Vichai Srivaddhanaprabha in 2018 devastated the club. After relegation in 2023 and 2024, Leicester are rebuilding.`,
    recentForm: 'Leicester are rebuilding in the Premier League under Steve Cooper.',
    keyFacts: [
      'The 2015/16 Premier League title win is the greatest sporting upset ever — 5000-1 odds',
      'Claudio Ranieri\'s "dilly-ding, dilly-dong" became a cultural moment',
      'Jamie Vardy set a Premier League record of scoring in 11 consecutive matches',
      'Owner Vichai Srivaddhanaprabha\'s tragic death in 2018 shocked the world',
      'Won their first FA Cup in 2021 under Brendan Rodgers',
      'King Power Stadium has been their home since 2002',
    ],
    colors: 'Blue and White',
    rivals: ['Nottingham Forest', 'Derby County', 'Coventry City'],
    schema: { foundingDate: '1884', location: 'Leicester, England', alternateName: 'The Foxes' },
  },
  'ipswich': {
    slug: 'ipswich',
    founded: 1878,
    stadium: 'Portman Road',
    stadiumCapacity: 30311,
    city: 'Ipswich',
    country: 'England',
    nickname: 'The Tractor Boys',
    manager: 'Kieran McKenna',
    website: 'https://www.itfc.co.uk',
    trophies: [
      { label: 'First Division', count: 1 },
      { label: 'FA Cup', count: 1 },
      { label: 'UEFA Cup', count: 1 },
    ],
    history: `Ipswich Town, founded in 1878, enjoyed their greatest era under Sir Bobby Robson, winning the First Division in 1962 and famously the UEFA Cup in 1981 — a remarkable achievement for a provincial club. The club fell through the divisions after years of mismanagement but a stunning back-to-back promotion under Kieran McKenna took them from League One to the Premier League in just two seasons, culminating in a return to the top flight for the first time since 2002.`,
    recentForm: 'Ipswich are enjoying their Premier League return under the highly-rated Kieran McKenna.',
    keyFacts: [
      'Won the UEFA Cup in 1981 under Sir Bobby Robson — one of English football\'s great achievements',
      'Back-to-back promotions from League One to Premier League (2022–2024)',
      'Kieran McKenna is regarded as one of the brightest young managers in world football',
      'Sir Bobby Robson later managed England, winning the 1990 World Cup bronze medal',
      'Portman Road has been their home since 1884',
      'First Premier League season since 2002',
    ],
    colors: 'Blue and White',
    rivals: ['Norwich City'],
    schema: { foundingDate: '1878', location: 'Ipswich, England' },
  },
  'bournemouth': {
    slug: 'bournemouth',
    founded: 1899,
    stadium: 'Vitality Stadium',
    stadiumCapacity: 11307,
    city: 'Bournemouth',
    country: 'England',
    nickname: 'The Cherries',
    manager: 'Andoni Iraola',
    website: 'https://www.afcb.co.uk',
    trophies: [{ label: 'Second Division', count: 1 }],
    history: `AFC Bournemouth, founded in 1899, were a non-league club until the 1920s and spent most of their existence in the lower divisions. Eddie Howe's transformative management took them from League Two in 2009 to the Premier League by 2015, where they spent five seasons, famously beating Liverpool and Manchester United along the way. After relegation in 2020 and immediate return, the club has established itself under Andoni Iraola. The Vitality Stadium, with a capacity of just 11,307, is the smallest in the Premier League.`,
    recentForm: 'Bournemouth continue to punch above their weight under Andoni Iraola.',
    keyFacts: [
      'The Vitality Stadium is the smallest ground in the Premier League (11,307 capacity)',
      'Eddie Howe took the club from League Two to the Premier League in six years',
      'Famously beat Manchester United 1-0 at Old Trafford in 2016',
      'Andoni Iraola\'s pressing style has impressed the Premier League',
      'Their red cherry badge is one of the most distinctive in English football',
      'Jaidon Anthony, Dominic Solanke and David Brooks are notable academy products',
    ],
    colors: 'Red and Black',
    rivals: ['Southampton', 'Portsmouth'],
    schema: { foundingDate: '1899', location: 'Bournemouth, England', alternateName: 'The Cherries' },
  },

  // ── LA LIGA ─────────────────────────────────────────────────────────────────
  'barcelona': {
    slug: 'barcelona',
    founded: 1899,
    stadium: 'Spotify Camp Nou',
    stadiumCapacity: 99354,
    city: 'Barcelona',
    country: 'Spain',
    nickname: 'Barça / Blaugrana',
    manager: 'Hansi Flick',
    website: 'https://www.fcbarcelona.com',
    trophies: [
      { label: 'La Liga', count: 27 },
      { label: 'UEFA Champions League', count: 5 },
      { label: 'Copa del Rey', count: 31 },
      { label: 'FIFA Club World Cup', count: 3 },
      { label: 'UEFA Super Cup', count: 5 },
    ],
    history: `FC Barcelona was founded in 1899 by Swiss businessman Joan Gamper and has become one of the most recognised sports clubs in the world. "Més que un club" (More than a club) reflects their deep connection to Catalan identity. Johan Cruyff's influence as player and manager defined the club's "tiki-taka" DNA. The Pep Guardiola era (2008–2012) produced arguably the greatest club side ever, winning six trophies in one year. Lionel Messi's 17-year association, during which he scored 672 goals, makes him the greatest player in the club's history.`,
    recentForm: 'Under Hansi Flick, Barcelona are rebuilding with a talented young squad.',
    keyFacts: [
      '"Més que un club" — the club represents Catalan cultural identity',
      'Lionel Messi scored 672 goals in 778 appearances for the club',
      'Camp Nou is Europe\'s largest stadium (99,354 capacity)',
      'Pep Guardiola\'s team won 6 trophies in 2009 — an unprecedented sextuple',
      'Johan Cruyff\'s Total Football philosophy shapes the club\'s identity',
      'La Masia academy has produced Messi, Xavi, Iniesta, Busquets and many more',
    ],
    colors: 'Blue and Red (Blaugrana)',
    rivals: ['Real Madrid (El Clásico)', 'Espanyol', 'Atlético Madrid'],
    schema: { foundingDate: '1899', location: 'Barcelona, Spain', alternateName: 'Barça' },
  },
  'real-madrid': {
    slug: 'real-madrid',
    founded: 1902,
    stadium: 'Santiago Bernabéu',
    stadiumCapacity: 81044,
    city: 'Madrid',
    country: 'Spain',
    nickname: 'Los Blancos / Los Merengues',
    manager: 'Carlo Ancelotti',
    website: 'https://www.realmadrid.com',
    trophies: [
      { label: 'La Liga', count: 36 },
      { label: 'UEFA Champions League', count: 15 },
      { label: 'Copa del Rey', count: 20 },
      { label: 'FIFA Club World Cup', count: 8 },
      { label: 'UEFA Super Cup', count: 5 },
    ],
    history: `Real Madrid CF, founded in 1902, is the most successful club in the history of the UEFA Champions League, having won it a record 15 times. Under legendary president Santiago Bernabéu, the club assembled the "Galácticos" of the 1950s — including Alfredo Di Stéfano and Ferenc Puskás — who won five consecutive European Cups. The modern era has been defined by Cristiano Ronaldo (450 goals, 2009–2018) and Zinedine Zidane's managerial genius. Under Carlo Ancelotti, they won their 14th and 15th Champions League titles in 2022 and 2024.`,
    recentForm: 'Real Madrid remain Europe\'s dominant force under Carlo Ancelotti.',
    keyFacts: [
      'Record 15 UEFA Champions League titles',
      'Cristiano Ronaldo scored 450 goals in 438 appearances',
      'Won five consecutive European Cups from 1956–1960',
      'The Santiago Bernabéu has been renovated into a state-of-the-art 81,044-seat arena',
      'Zinedine Zidane won 3 consecutive Champions League titles as manager (2016–2018)',
      'Alfredo Di Stéfano is considered the club\'s greatest ever player',
    ],
    colors: 'White',
    rivals: ['Barcelona (El Clásico)', 'Atlético Madrid', 'Valencia'],
    schema: { foundingDate: '1902', location: 'Madrid, Spain', alternateName: 'Los Blancos' },
  },
  'atletico-madrid': {
    slug: 'atletico-madrid',
    founded: 1903,
    stadium: 'Estadio Metropolitano',
    stadiumCapacity: 68456,
    city: 'Madrid',
    country: 'Spain',
    nickname: 'Los Colchoneros',
    manager: 'Diego Simeone',
    website: 'https://www.atleticodemadrid.com',
    trophies: [
      { label: 'La Liga', count: 11 },
      { label: 'UEFA Europa League', count: 3 },
      { label: 'Copa del Rey', count: 10 },
      { label: 'UEFA Super Cup', count: 1 },
      { label: 'FIFA Club World Cup', count: 1 },
    ],
    history: `Atlético de Madrid, founded in 1903, are known as the "Colchoneros" (the Mattress Makers) due to their red-and-white striped colours. Under Diego Simeone's leadership since 2011, Atlético have become one of Europe's top clubs, winning two La Liga titles, three Europa Leagues and reaching two Champions League finals. Their move to the Estadio Metropolitano in 2017, with a capacity of 68,456, marked a new era. Antoine Griezmann and Diego Godín are among their greatest modern players.`,
    recentForm: 'Atlético Madrid remain La Liga title contenders under Diego Simeone.',
    keyFacts: [
      'Diego Simeone is one of the longest-serving and most successful managers in European football',
      'Won La Liga in 2014 and 2021, breaking the Barcelona-Real Madrid duopoly',
      'Record three-time UEFA Europa League winners',
      'Moved to the state-of-the-art Metropolitano Stadium in 2017',
      'Famous for their defensive organisation and fighting spirit',
      'Fernando Torres is one of the club\'s greatest ever players',
    ],
    colors: 'Red and White stripes',
    rivals: ['Real Madrid', 'Barcelona', 'Getafe'],
    schema: { foundingDate: '1903', location: 'Madrid, Spain', alternateName: 'Los Colchoneros' },
  },
  'barcelona-rivals': { slug: 'valencia', founded: 1919, stadium: 'Mestalla', stadiumCapacity: 49430, city: 'Valencia', country: 'Spain', nickname: 'Los Ches', manager: 'Carlos Corberán', website: 'https://www.valenciacf.com', trophies: [{ label: 'La Liga', count: 6 }, { label: 'UEFA Europa League', count: 1 }, { label: 'Copa del Rey', count: 8 }, { label: 'UEFA Cup Winners\' Cup', count: 1 }], history: 'Valencia CF, founded in 1919, are one of Spain\'s most decorated clubs, winning La Liga six times and reaching the Champions League final twice in the early 2000s.', recentForm: 'Valencia are rebuilding under Carlos Corberán.', keyFacts: ['Six La Liga titles', 'Champions League finalists in 2000 and 2001', 'Mestalla is one of Spain\'s most atmospheric grounds'], colors: 'White and Orange', rivals: ['Villarreal', 'Levante', 'Alicante'], schema: { foundingDate: '1919', location: 'Valencia, Spain' } },
  'valencia': {
    slug: 'valencia',
    founded: 1919,
    stadium: 'Mestalla',
    stadiumCapacity: 49430,
    city: 'Valencia',
    country: 'Spain',
    nickname: 'Los Ches',
    manager: 'Carlos Corberán',
    website: 'https://www.valenciacf.com',
    trophies: [
      { label: 'La Liga', count: 6 },
      { label: 'UEFA Europa League / UEFA Cup', count: 1 },
      { label: 'Copa del Rey', count: 8 },
    ],
    history: `Valencia CF, founded in 1919, are one of Spain's most historic clubs. Their golden era came in the early 2000s under Héctor Cúper and then Rafael Benítez, reaching the Champions League final in consecutive years (2000, 2001) and winning two La Liga titles. Mestalla is one of Spain's most famous and atmospheric stadiums. The club has faced financial difficulties in recent years but remains a significant force in Spanish football.`,
    recentForm: 'Valencia are rebuilding under Carlos Corberán.',
    keyFacts: ['Six La Liga titles', 'Champions League finalists in 2000 and 2001', 'Mestalla opened in 1923 and seats 49,430', 'David Villa and David Silva are famous academy products', 'Rafael Benítez delivered two La Liga titles in the early 2000s'],
    colors: 'White and Orange',
    rivals: ['Villarreal', 'Levante'],
    schema: { foundingDate: '1919', location: 'Valencia, Spain' },
  },
  'real-betis': {
    slug: 'real-betis',
    founded: 1907,
    stadium: 'Estadio Benito Villamarín',
    stadiumCapacity: 60721,
    city: 'Seville',
    country: 'Spain',
    nickname: 'Los Verdiblancos',
    manager: 'Manuel Pellegrini',
    website: 'https://www.realbetisbalompie.es',
    trophies: [{ label: 'La Liga', count: 1 }, { label: 'Copa del Rey', count: 3 }, { label: 'UEFA Europa League', count: 1 }],
    history: 'Real Betis Balompié, founded in 1907, won their only La Liga title in 1935 and are beloved for their passionate "Béticos" supporters. Manuel Pellegrini has established them as a consistent Europa League contender.',
    recentForm: 'Betis are performing well under Manuel Pellegrini\'s experienced leadership.',
    keyFacts: ['Won the UEFA Europa League in 2022 under Manuel Pellegrini', 'Estadio Benito Villamarín holds 60,721 fans', 'Sergio Canales was a beloved figure at the club', 'Famous for their passionate green-and-white supporters'],
    colors: 'Green and White',
    rivals: ['Sevilla (El Gran Derbi)'],
    schema: { foundingDate: '1907', location: 'Seville, Spain' },
  },
  'sevilla': {
    slug: 'sevilla',
    founded: 1890,
    stadium: 'Ramón Sánchez Pizjuán',
    stadiumCapacity: 43883,
    city: 'Seville',
    country: 'Spain',
    nickname: 'Los Rojiblancos',
    manager: 'Francisco',
    website: 'https://www.sevillafc.es',
    trophies: [{ label: 'La Liga', count: 1 }, { label: 'UEFA Europa League', count: 7 }, { label: 'Copa del Rey', count: 5 }],
    history: 'Sevilla FC, founded in 1890, are the most successful club in UEFA Europa League history, having won it a record seven times. Their famous Sporting Director Monchi built a world-class scouting network that funded success while selling players at profit.',
    recentForm: 'Sevilla are working to return to their best under new management.',
    keyFacts: ['Record 7 UEFA Europa League titles', 'Monchi\'s transfer model is studied worldwide', 'Ramón Sánchez Pizjuán has a fierce atmosphere', 'Jesús Navas is a club legend who returned after years at Man City'],
    colors: 'Red and White',
    rivals: ['Real Betis (El Gran Derbi)'],
    schema: { foundingDate: '1890', location: 'Seville, Spain' },
  },
  'villarreal': {
    slug: 'villarreal',
    founded: 1923,
    stadium: 'Estadio de la Cerámica',
    stadiumCapacity: 23500,
    city: 'Villarreal',
    country: 'Spain',
    nickname: 'El Submarino Amarillo',
    manager: 'Marcelino',
    website: 'https://www.villarrealcf.es',
    trophies: [{ label: 'UEFA Europa League', count: 1 }],
    history: 'Villarreal CF, the "Yellow Submarine," punches far above its weight for a club from a city of just 50,000 people. They won the UEFA Europa League in 2021 under Unai Emery and reached the Champions League semi-finals.',
    recentForm: 'Villarreal continue to compete in the upper half of La Liga.',
    keyFacts: ['Won the UEFA Europa League in 2021 under Unai Emery', 'City population of just 50,000 — a remarkable story', 'Known as "El Submarino Amarillo" — The Yellow Submarine', 'Santi Cazorla returned to end his career at his hometown club'],
    colors: 'Yellow',
    rivals: ['Valencia', 'Espanyol'],
    schema: { foundingDate: '1923', location: 'Villarreal, Spain' },
  },
  'athletic-bilbao': {
    slug: 'athletic-bilbao',
    founded: 1898,
    stadium: 'San Mamés',
    stadiumCapacity: 53289,
    city: 'Bilbao',
    country: 'Spain',
    nickname: 'Los Leones',
    manager: 'Ernesto Valverde',
    website: 'https://www.athletic-club.eus',
    trophies: [{ label: 'La Liga', count: 8 }, { label: 'Copa del Rey', count: 24 }],
    history: 'Athletic Club Bilbao, founded in 1898, have a unique "Cantera" policy of only fielding players from the Basque Country. Despite this restriction, they have never been relegated from La Liga — one of only three clubs with this distinction alongside Real Madrid and Barcelona.',
    recentForm: 'Athletic Bilbao are competing strongly in La Liga under Ernesto Valverde.',
    keyFacts: ['Only field players from the Basque Country — a unique global policy', 'Never relegated from La Liga in their history', 'Record 24 Copa del Rey wins', 'San Mamés is known as "La Catedral"', 'Joseba Etxeberria and Julen Guerrero are club legends'],
    colors: 'Red and White stripes',
    rivals: ['Real Sociedad (Basque Derby)', 'Osasuna'],
    schema: { foundingDate: '1898', location: 'Bilbao, Spain', alternateName: 'Athletic Club' },
  },
  'real-sociedad': {
    slug: 'real-sociedad',
    founded: 1909,
    stadium: 'Reale Arena',
    stadiumCapacity: 39500,
    city: 'San Sebastián',
    country: 'Spain',
    nickname: 'La Real',
    manager: 'Imanol Alguacil',
    website: 'https://www.realsociedad.eus',
    trophies: [{ label: 'La Liga', count: 2 }, { label: 'Copa del Rey', count: 3 }],
    history: 'Real Sociedad, founded in 1909, won back-to-back La Liga titles in 1981 and 1982. The Basque club has a strong tradition of developing local talent and playing attractive football under Imanol Alguacil.',
    recentForm: 'Real Sociedad are competing well in La Liga and European competitions.',
    keyFacts: ['Back-to-back La Liga champions in 1981 and 1982', 'Strong Basque identity and local player development', 'Mikel Oyarzabal is the current captain and star player', 'Based in San Sebastián, the culinary capital of Spain'],
    colors: 'Blue and White',
    rivals: ['Athletic Bilbao (Basque Derby)'],
    schema: { foundingDate: '1909', location: 'San Sebastián, Spain' },
  },
  'girona': {
    slug: 'girona',
    founded: 1930,
    stadium: 'Montilivi',
    stadiumCapacity: 13450,
    city: 'Girona',
    country: 'Spain',
    nickname: 'Els Vermells',
    manager: 'Míchel',
    website: 'https://www.gironafc.cat',
    trophies: [{ label: 'Segunda División', count: 2 }],
    history: 'Girona FC, founded in 1930, made history in 2023/24 by finishing third in La Liga and qualifying for the Champions League for the first time — a stunning achievement for a club from a city of 100,000 people. Connected to the City Football Group, their rise under Míchel has been one of football\'s great recent stories.',
    recentForm: 'Girona are building on their remarkable 2023/24 Champions League qualification.',
    keyFacts: ['Qualified for the Champions League for the first time in 2024', 'Finished 3rd in La Liga in 2023/24 — one of football\'s great upsets', 'Connected to City Football Group', 'Artem Dovbyk was La Liga\'s top scorer in 2023/24', 'Coach Míchel is one of Spain\'s most exciting managers'],
    colors: 'Red and White',
    rivals: ['Barcelona', 'Espanyol'],
    schema: { foundingDate: '1930', location: 'Girona, Spain' },
  },

  // ── BUNDESLIGA ───────────────────────────────────────────────────────────────
  'bayern-munich': {
    slug: 'bayern-munich',
    founded: 1900,
    stadium: 'Allianz Arena',
    stadiumCapacity: 75024,
    city: 'Munich',
    country: 'Germany',
    nickname: 'Die Roten / FC Hollywood',
    manager: 'Vincent Kompany',
    website: 'https://www.fcbayern.com',
    trophies: [
      { label: 'Bundesliga', count: 32 },
      { label: 'UEFA Champions League', count: 6 },
      { label: 'DFB-Pokal', count: 20 },
      { label: 'FIFA Club World Cup', count: 2 },
      { label: 'UEFA Super Cup', count: 2 },
    ],
    history: `FC Bayern Munich, founded in 1900, are Germany's most successful club and one of the world's elite. Their Bundesliga dominance includes 32 titles and 11 consecutive championships between 2013 and 2023. Under Jupp Heynckes in 2012/13, Bayern won a historic treble. The Allianz Arena, opened in 2005, is one of the world's most modern and iconic stadiums, famous for turning red on match nights. Legendary players include Franz Beckenbauer, Gerd Müller, Oliver Kahn and Thomas Müller.`,
    recentForm: 'Bayern Munich are rebuilding under Vincent Kompany after their dominant era.',
    keyFacts: ['32 Bundesliga titles — more than any other club', 'Six UEFA Champions League titles', '11 consecutive Bundesliga titles (2013–2023)', 'The Allianz Arena turns red on match nights for an iconic visual effect', 'Franz Beckenbauer — "Der Kaiser" — is the club\'s greatest ever player', 'Thomas Müller has spent his entire career at the club'],
    colors: 'Red and White',
    rivals: ['Borussia Dortmund (Der Klassiker)', 'TSV 1860 Munich'],
    schema: { foundingDate: '1900', location: 'Munich, Germany', alternateName: 'Die Roten' },
  },
  'borussia-dortmund': {
    slug: 'borussia-dortmund',
    founded: 1909,
    stadium: 'Signal Iduna Park',
    stadiumCapacity: 81365,
    city: 'Dortmund',
    country: 'Germany',
    nickname: 'BVB / Die Schwarzgelben',
    manager: 'Niko Kovač',
    website: 'https://www.bvb.de',
    trophies: [{ label: 'Bundesliga', count: 8 }, { label: 'UEFA Champions League', count: 1 }, { label: 'DFB-Pokal', count: 5 }, { label: 'UEFA Cup Winners\' Cup', count: 1 }],
    history: 'Borussia Dortmund, founded in 1909, are Germany\'s second most successful club and the only serious challenger to Bayern Munich. Their Signal Iduna Park features the iconic "Yellow Wall" — the largest standing terrace in European football with 25,000 fans. Under Jürgen Klopp (2008–2015) they won back-to-back Bundesliga titles and reached the Champions League final in 2013.',
    recentForm: 'BVB reached the Champions League final again in 2024 under Edin Terzić.',
    keyFacts: ['The "Yellow Wall" is Europe\'s largest terrace (25,000 standing)', 'Champions League finalists in 2013 and 2024', 'Jürgen Klopp\'s "heavy metal football" defined an era', 'Robert Lewandowski scored his famous 5 goals in 9 minutes here in 2015', 'The club went bankrupt in 2003 and rebuilt — a remarkable story', 'Signal Iduna Park is Germany\'s largest stadium'],
    colors: 'Yellow and Black',
    rivals: ['Bayern Munich (Der Klassiker)', 'Schalke (Revierderby)'],
    schema: { foundingDate: '1909', location: 'Dortmund, Germany', alternateName: 'BVB' },
  },
  'rb-leipzig': {
    slug: 'rb-leipzig',
    founded: 2009,
    stadium: 'Red Bull Arena',
    stadiumCapacity: 47069,
    city: 'Leipzig',
    country: 'Germany',
    nickname: 'Die Roten Bullen',
    manager: 'Marco Rose',
    website: 'https://www.rbleipzig.com',
    trophies: [{ label: 'DFB-Pokal', count: 1 }],
    history: 'RB Leipzig, founded in 2009 as Red Bull\'s German project, rose from the fifth division to the Bundesliga in just seven years. Their rapid rise has been controversial among traditional football fans, but they have firmly established themselves in the Bundesliga top four and European competition.',
    recentForm: 'RB Leipzig continue to compete for the Bundesliga title and in European football.',
    keyFacts: ['Rose from 5th division to Bundesliga in just 7 years', 'Timo Werner is a notable product of the club', 'Won the DFB-Pokal in 2022', 'Part of the Red Bull network alongside Salzburg and New York', 'Christopher Nkunku was sold to Chelsea for €60m in 2023'],
    colors: 'Red and White',
    rivals: ['Borussia Dortmund', 'Bayern Munich'],
    schema: { foundingDate: '2009', location: 'Leipzig, Germany' },
  },
  'bayer-leverkusen': {
    slug: 'bayer-leverkusen',
    founded: 1904,
    stadium: 'BayArena',
    stadiumCapacity: 30210,
    city: 'Leverkusen',
    country: 'Germany',
    nickname: 'Die Werkself / Neverkusen (former)',
    manager: 'Xabi Alonso',
    website: 'https://www.bayer04.de',
    trophies: [{ label: 'Bundesliga', count: 1 }, { label: 'DFB-Pokal', count: 1 }, { label: 'UEFA Cup', count: 1 }],
    history: 'Bayer 04 Leverkusen, founded in 1904 as the sports club of Bayer pharmaceutical company, were long known as "Neverkusen" for finishing runners-up. All that changed under Xabi Alonso in 2023/24, when they won their first Bundesliga title unbeaten — one of the most remarkable achievements in European football history.',
    recentForm: 'Leverkusen are defending Bundesliga champions under the brilliant Xabi Alonso.',
    keyFacts: ['Won their first ever Bundesliga title in 2023/24 — unbeaten all season', 'Xabi Alonso is widely regarded as Europe\'s best young manager', 'Previously known as "Neverkusen" for finishing second so often', 'Granit Xhaka was transformed under Alonso into a key player', 'The BayArena is one of Germany\'s most modern stadiums', 'Michael Ballack and Rudi Völler are famous former players'],
    colors: 'Red and Black',
    rivals: ['Cologne', 'Borussia Mönchengladbach'],
    schema: { foundingDate: '1904', location: 'Leverkusen, Germany' },
  },
  'eintracht-frankfurt': {
    slug: 'eintracht-frankfurt',
    founded: 1899,
    stadium: 'Deutsche Bank Park',
    stadiumCapacity: 58000,
    city: 'Frankfurt',
    country: 'Germany',
    nickname: 'Die Adler',
    manager: 'Dino Toppmöller',
    website: 'https://www.eintracht.de',
    trophies: [{ label: 'Bundesliga', count: 1 }, { label: 'DFB-Pokal', count: 5 }, { label: 'UEFA Europa League', count: 2 }],
    history: 'Eintracht Frankfurt, founded in 1899, have one of the most passionate fanbases in Germany. Their UEFA Europa League win in 2022 under Oliver Glasner was particularly celebrated — 30,000 Frankfurt fans filled Celtic Park in the semi-final, creating an extraordinary atmosphere. The club have a tradition of exciting, attacking football.',
    recentForm: 'Frankfurt are competing for European football spots in the Bundesliga.',
    keyFacts: ['Won the UEFA Europa League in 2022 under Oliver Glasner', '30,000 Frankfurt fans at Celtic Park in the Europa League semi-final is legendary', 'Deutsche Bank Park holds 58,000 fans', 'Kevin Trapp is a long-serving and beloved goalkeeper', 'Rafael Borré scored the winning penalty in the 2022 Europa League final'],
    colors: 'Red, Black and White',
    rivals: ['Borussia Dortmund', 'Bayern Munich', 'Kaiserslautern'],
    schema: { foundingDate: '1899', location: 'Frankfurt, Germany', alternateName: 'Die Adler' },
  },
  'vfb-stuttgart': {
    slug: 'vfb-stuttgart',
    founded: 1893,
    stadium: 'MHPArena',
    stadiumCapacity: 60449,
    city: 'Stuttgart',
    country: 'Germany',
    nickname: 'Die Schwaben',
    manager: 'Sebastian Hoeneß',
    website: 'https://www.vfb.de',
    trophies: [{ label: 'Bundesliga', count: 5 }, { label: 'DFB-Pokal', count: 3 }],
    history: 'VfB Stuttgart, founded in 1893, are one of Germany\'s traditional clubs with five Bundesliga titles. After near-relegation battles, Stuttgart have rebuilt under Sebastian Hoeneß and Sporting Director Fabian Wohlgemuth into a top-four Bundesliga force, with young stars Florian Wirtz (on loan) and Chris Führich shining.',
    recentForm: 'Stuttgart are competing strongly in the top half of the Bundesliga.',
    keyFacts: ['Five Bundesliga titles (last won 2007)', 'Produced legends including Fredi Bobic and Giovane Élber', 'The MHPArena held Euro 2024 matches', 'Chris Führich and Deniz Undav have been key to their recent success', 'Narrowly avoided relegation in 2022/23 then finished 2nd in 2023/24'],
    colors: 'Red and White',
    rivals: ['Karlsruhe', 'Freiburg'],
    schema: { foundingDate: '1893', location: 'Stuttgart, Germany' },
  },
  'wolfsburg': {
    slug: 'wolfsburg',
    founded: 1945,
    stadium: 'Volkswagen Arena',
    stadiumCapacity: 30000,
    city: 'Wolfsburg',
    country: 'Germany',
    nickname: 'Die Wölfe',
    manager: 'Ralph Hasenhüttl',
    website: 'https://www.vfl-wolfsburg.de',
    trophies: [{ label: 'Bundesliga', count: 1 }, { label: 'DFB-Pokal', count: 1 }, { label: 'UEFA Champions League (Women)', count: 5 }],
    history: 'VfL Wolfsburg, founded in 1945 as the works club of Volkswagen, won their first Bundesliga title in 2009 — a huge achievement for a club of their size. Their women\'s team is one of the most decorated in world football, winning five Champions League titles.',
    recentForm: 'Wolfsburg are working to establish themselves in the Bundesliga top half.',
    keyFacts: ['Won the Bundesliga in 2009 with a record 5-1 away win on the final day', 'Women\'s team has won 5 Champions League titles — one of the most successful ever', 'Owned and funded by Volkswagen', 'Edin Džeko\'s 26 league goals in 2009 were crucial to the title win', 'Kevin De Bruyne played here before moving to Chelsea and then Man City'],
    colors: 'Green and White',
    rivals: ['Hannover', 'Eintracht Braunschweig'],
    schema: { foundingDate: '1945', location: 'Wolfsburg, Germany', alternateName: 'Die Wölfe' },
  },
  'borussia-monchengladbach': {
    slug: 'borussia-monchengladbach',
    founded: 1900,
    stadium: 'Borussia-Park',
    stadiumCapacity: 54057,
    city: 'Mönchengladbach',
    country: 'Germany',
    nickname: 'Die Fohlen',
    manager: 'Gerardo Seoane',
    website: 'https://www.borussia.de',
    trophies: [{ label: 'Bundesliga', count: 5 }, { label: 'DFB-Pokal', count: 3 }, { label: 'UEFA Cup', count: 2 }],
    history: 'Borussia Mönchengladbach, founded in 1900, were Germany\'s dominant club in the 1970s under coach Hennes Weisweiler, winning five Bundesliga titles and two UEFA Cups. Their attacking "Fohlenelf" (Foal Eleven) style was celebrated across Europe. They have struggled to recapture those heights in recent decades.',
    recentForm: 'Gladbach are working to return to the Bundesliga\'s top half.',
    keyFacts: ['Five Bundesliga titles in the 1970s — a golden era', 'Two consecutive UEFA Cup wins (1975, 1979)', 'Günter Netzer was the iconic playmaker of the golden generation', 'Borussia-Park stadium opened in 2004 with 54,057 capacity', 'Famous rivalry with Köln (Rhine Derby)'],
    colors: 'Black and White',
    rivals: ['Cologne (Rhine Derby)', 'Bayer Leverkusen'],
    schema: { foundingDate: '1900', location: 'Mönchengladbach, Germany', alternateName: 'Die Fohlen' },
  },
  'union-berlin': {
    slug: 'union-berlin',
    founded: 1906,
    stadium: 'Stadion An der Alten Försterei',
    stadiumCapacity: 22012,
    city: 'Berlin',
    country: 'Germany',
    nickname: 'Die Eisernen',
    manager: 'Bo Svensson',
    website: 'https://www.fc-union-berlin.de',
    trophies: [{ label: 'DFB-Pokal', count: 0 }],
    history: 'Union Berlin, founded in 1906 in East Berlin, have a remarkable story. Beloved for their working-class ethos and fans who helped build their stadium with their own hands, they made their Bundesliga debut in 2019 and stunned everyone by qualifying for European football in consecutive seasons.',
    recentForm: 'Union Berlin are adjusting after their remarkable European seasons.',
    keyFacts: ['Fans helped rebuild the Alte Försterei stadium in 2009 with their own labour', 'Made their Bundesliga debut in 2019 after decades in lower divisions', 'Christmas carol singing tradition at the stadium is beloved', 'Distinguished East Berlin club with a fierce working-class identity', 'Qualified for the Europa League in 2022 and Champions League in 2023'],
    colors: 'Red and White',
    rivals: ['Hertha Berlin (Berlin Derby)'],
    schema: { foundingDate: '1906', location: 'Berlin, Germany', alternateName: 'Die Eisernen' },
  },
  'werder-bremen': {
    slug: 'werder-bremen',
    founded: 1899,
    stadium: 'wohninvest Weserstadion',
    stadiumCapacity: 42100,
    city: 'Bremen',
    country: 'Germany',
    nickname: 'Die Werderaner',
    manager: 'Ole Werner',
    website: 'https://www.werder.de',
    trophies: [{ label: 'Bundesliga', count: 4 }, { label: 'DFB-Pokal', count: 6 }, { label: 'UEFA Cup Winners\' Cup', count: 1 }],
    history: 'Werder Bremen, founded in 1899, are one of Germany\'s traditional clubs. Their greatest era came in the 1980s and early 2000s under Otto Rehhagel and Thomas Schaaf respectively. They won the Bundesliga four times and the Cup Winners\' Cup in 1992. After a dramatic relegation in 2021, they bounced back in 2022 under Ole Werner.',
    recentForm: 'Bremen are enjoying life back in the Bundesliga under Ole Werner.',
    keyFacts: ['Four Bundesliga titles and six DFB-Pokal wins', 'Won the Cup Winners\' Cup in 1992', 'Claudio Pizarro scored 197 Bundesliga goals for the club — a foreign-player record', 'Relegated in 2021 after 40 consecutive Bundesliga seasons', 'Promoted back in 2022 — an emotional return'],
    colors: 'Green and White',
    rivals: ['Hamburg', 'Hannover 96'],
    schema: { foundingDate: '1899', location: 'Bremen, Germany' },
  },

  // ── SERIE A ──────────────────────────────────────────────────────────────────
  'ac-milan': {
    slug: 'ac-milan',
    founded: 1899,
    stadium: 'San Siro',
    stadiumCapacity: 75817,
    city: 'Milan',
    country: 'Italy',
    nickname: 'Il Diavolo / Rossoneri',
    manager: 'Sérgio Conceição',
    website: 'https://www.acmilan.com',
    trophies: [{ label: 'Serie A', count: 19 }, { label: 'UEFA Champions League', count: 7 }, { label: 'Coppa Italia', count: 5 }, { label: 'FIFA Club World Cup', count: 1 }],
    history: 'AC Milan, founded in 1899, are one of the world\'s most storied clubs with 7 Champions League titles. Their golden eras came under Arrigo Sacchi in the late 1980s (with a brilliant Dutch trio of Gullit, Rijkaard and Van Basten) and Carlo Ancelotti in the 2000s. After years in Inter\'s shadow, Milan returned to the Serie A throne in 2021/22 under Stefano Pioli.',
    recentForm: 'Milan are competing for Serie A honours under Sérgio Conceição.',
    keyFacts: ['Seven UEFA Champions League titles — joint second most in history', 'Gullit, Rijkaard and Van Basten formed one of football\'s greatest ever trios', 'Won Serie A in 2021/22 — first title in 11 years', 'San Siro (Giuseppe Meazza) is shared with Inter Milan', 'Paolo Maldini\'s 25-year playing career at the club is legendary', 'Carlo Ancelotti won 2 Champions Leagues as manager'],
    colors: 'Red and Black',
    rivals: ['Inter Milan (Derby della Madonnina)', 'Juventus'],
    schema: { foundingDate: '1899', location: 'Milan, Italy', alternateName: 'Rossoneri' },
  },
  'inter-milan': {
    slug: 'inter-milan',
    founded: 1908,
    stadium: 'San Siro',
    stadiumCapacity: 75817,
    city: 'Milan',
    country: 'Italy',
    nickname: 'La Beneamata / Nerazzurri',
    manager: 'Simone Inzaghi',
    website: 'https://www.inter.it',
    trophies: [{ label: 'Serie A', count: 20 }, { label: 'UEFA Champions League', count: 3 }, { label: 'Coppa Italia', count: 9 }, { label: 'FIFA Club World Cup', count: 2 }],
    history: 'FC Internazionale Milano, founded in 1908, won an historic treble in 2009/10 under José Mourinho — Serie A, Coppa Italia and Champions League. The club dominated Italian football in the late 2000s under Massimo Moratti\'s ownership. Under Simone Inzaghi, they have re-established Serie A dominance, winning the Scudetto in 2023/24 and reaching the Champions League final in 2023.',
    recentForm: 'Inter are Serie A champions and competing at the top of European football.',
    keyFacts: ['Won the historic treble under José Mourinho in 2009/10', 'Sandro Mazzola and Javier Zanetti are legendary figures', 'Ronaldo (the original) wore the Inter shirt from 1997–2002', 'Champions League finalists in 2023 under Simone Inzaghi', 'Lautaro Martínez is the current captain and top scorer', 'Serie A champions 2023/24 — the "second star" on their shirt'],
    colors: 'Blue and Black (Nerazzurri)',
    rivals: ['AC Milan (Derby della Madonnina)', 'Juventus'],
    schema: { foundingDate: '1908', location: 'Milan, Italy', alternateName: 'Nerazzurri' },
  },
  'juventus': {
    slug: 'juventus',
    founded: 1897,
    stadium: 'Allianz Stadium',
    stadiumCapacity: 41507,
    city: 'Turin',
    country: 'Italy',
    nickname: 'La Vecchia Signora',
    manager: 'Thiago Motta',
    website: 'https://www.juventus.com',
    trophies: [{ label: 'Serie A', count: 36 }, { label: 'UEFA Champions League', count: 2 }, { label: 'Coppa Italia', count: 15 }, { label: 'UEFA Europa League', count: 3 }],
    history: 'Juventus FC, "The Old Lady," founded in 1897, is Italy\'s most successful club with 36 Serie A titles. They dominated Italian football under Marcello Lippi and then Massimiliano Allegri, winning nine consecutive Serie A titles (2012–2020). Cristiano Ronaldo\'s three-year stint (2018–2021) brought global attention. The 2006 Calciopoli match-fixing scandal resulted in a forced relegation, but they bounced back to reclaim their dominant position.',
    recentForm: 'Juventus are rebuilding under Thiago Motta with a new, younger approach.',
    keyFacts: ['Italy\'s most successful club with 36 Serie A titles', 'Nine consecutive league titles from 2012–2020', 'Cristiano Ronaldo joined in 2018 for €112m — a Serie A record transfer', 'Forced to Serie B after 2006 Calciopoli match-fixing scandal', 'The Allianz Stadium was the first Italian ground entirely owned by the club', 'Pavel Nedvěd, Alessandro Del Piero and Roberto Baggio are all-time legends'],
    colors: 'Black and White',
    rivals: ['Inter Milan (Derby d\'Italia)', 'Torino (Derby della Mole)'],
    schema: { foundingDate: '1897', location: 'Turin, Italy', alternateName: 'La Vecchia Signora' },
  },
  'as-roma': {
    slug: 'as-roma',
    founded: 1927,
    stadium: 'Stadio Olimpico',
    stadiumCapacity: 70634,
    city: 'Rome',
    country: 'Italy',
    nickname: 'I Giallorossi',
    manager: 'Claudio Ranieri',
    website: 'https://www.asroma.com',
    trophies: [{ label: 'Serie A', count: 3 }, { label: 'Coppa Italia', count: 9 }, { label: 'UEFA Conference League', count: 1 }],
    history: 'AS Roma, founded in 1927, represent the capital city and have three Serie A titles. Their greatest recent achievement was winning the inaugural UEFA Conference League in 2022 under José Mourinho — their first European trophy. Francesco Totti, "Il Capitano," spent his entire 25-year career at the club and is one of football\'s greatest one-club men.',
    recentForm: 'Roma are rebuilding under the legendary Claudio Ranieri.',
    keyFacts: ['Won the inaugural UEFA Conference League in 2022', 'Francesco Totti played 786 games for the club — the ultimate one-club man', 'The Curva Sud ultras are among Italy\'s most passionate supporters', 'Claudio Ranieri — of Leicester fame — returned to manage his hometown club', 'Gabriel Batistuta scored 168 Serie A goals for the club', 'Deep rivalry with Lazio makes the Derby della Capitale one of Italy\'s fiercest'],
    colors: 'Red and Yellow (Giallorossi)',
    rivals: ['Lazio (Derby della Capitale)', 'Juventus'],
    schema: { foundingDate: '1927', location: 'Rome, Italy', alternateName: 'I Giallorossi' },
  },
  'napoli': {
    slug: 'napoli',
    founded: 1926,
    stadium: 'Stadio Diego Armando Maradona',
    stadiumCapacity: 54726,
    city: 'Naples',
    country: 'Italy',
    nickname: 'Gli Azzurri / Partenopei',
    manager: 'Antonio Conte',
    website: 'https://www.sscnapoli.it',
    trophies: [{ label: 'Serie A', count: 3 }, { label: 'Coppa Italia', count: 6 }, { label: 'UEFA Cup', count: 1 }],
    history: 'SSC Napoli, founded in 1926, are the pride of southern Italy. Diego Maradona\'s arrival in 1984 transformed the club — he almost single-handedly delivered two Serie A titles and a UEFA Cup, making him a god-like figure in the city. Their stadium was renamed in his honour after his death in 2020. In 2022/23, under Luciano Spalletti, Napoli won their third Serie A title in stunning fashion.',
    recentForm: 'Napoli are competing for Serie A honours under Antonio Conte.',
    keyFacts: ['Diego Maradona is revered as a deity in Naples — streets, shrines and the stadium bear his name', 'Won Serie A in 2022/23 under Spalletti with a record points tally for the title', 'Antonio Conte joined in 2024, bringing renewed ambition', 'Khvicha Kvaratskhelia is one of Europe\'s most exciting players', 'Victor Osimhen won the 2023 African Cup of Nations and is a global star', 'The Curva A creates one of Italy\'s most electric atmospheres'],
    colors: 'Blue and White (Sky Blue)',
    rivals: ['Roma', 'Juventus', 'Inter Milan'],
    schema: { foundingDate: '1926', location: 'Naples, Italy' },
  },
  'lazio': {
    slug: 'lazio',
    founded: 1900,
    stadium: 'Stadio Olimpico',
    stadiumCapacity: 70634,
    city: 'Rome',
    country: 'Italy',
    nickname: 'Le Aquile / Biancocelesti',
    manager: 'Marco Baroni',
    website: 'https://www.sslazio.it',
    trophies: [{ label: 'Serie A', count: 2 }, { label: 'Coppa Italia', count: 7 }, { label: 'UEFA Cup Winners\' Cup', count: 1 }, { label: 'UEFA Super Cup', count: 1 }],
    history: 'SS Lazio, founded in 1900, share the Olimpico with city rivals Roma. Their golden era came in the late 1990s under Sven-Göran Eriksson, winning a Serie A and Coppa Italia double in 2000. Ciro Immobile has been one of Serie A\'s most prolific scorers. The Rome derby — the Derby della Capitale — is one of Italian football\'s most intense rivalries.',
    recentForm: 'Lazio are competing for European spots under Marco Baroni.',
    keyFacts: ['Serie A champions in 2000 under Sven-Göran Eriksson', 'Ciro Immobile won four Serie A Golden Boot awards', 'The Derby della Capitale against Roma is one of Italy\'s fiercest rivalries', 'Won the Cup Winners\' Cup in 1999', 'Share the Olimpico stadium with AS Roma', 'Simone Inzaghi managed the club from 2016–2021'],
    colors: 'Light Blue and White',
    rivals: ['AS Roma (Derby della Capitale)', 'Juventus'],
    schema: { foundingDate: '1900', location: 'Rome, Italy', alternateName: 'Le Aquile' },
  },
  'fiorentina': {
    slug: 'fiorentina',
    founded: 1926,
    stadium: 'Stadio Artemio Franchi',
    stadiumCapacity: 43147,
    city: 'Florence',
    country: 'Italy',
    nickname: 'La Viola',
    manager: 'Raffaele Palladino',
    website: 'https://www.acffiorentina.com',
    trophies: [{ label: 'Serie A', count: 2 }, { label: 'Coppa Italia', count: 6 }, { label: 'UEFA Cup Winners\' Cup', count: 1 }],
    history: 'ACF Fiorentina, founded in 1926, are beloved for their distinctive purple (viola) strip. Their greatest era featured Gabriel Batistuta, who scored 168 Serie A goals for the club in one of Italian football\'s great loyalties. They won back-to-back scudetti in 1955–56 and 1968–69 and have twice reached the UEFA Cup final.',
    recentForm: 'Fiorentina are competing for European football under Raffaele Palladino.',
    keyFacts: ['Gabriel Batistuta — "Batigol" — scored 168 Serie A goals and is worshipped in Florence', 'Two Serie A titles (1956, 1969)', 'The distinctive purple strip is one of football\'s most recognisable', 'Twice reached the UEFA Cup final (1990, 1994)', 'Roberto Baggio grew up at the club before his move to Juventus sparked riots'],
    colors: 'Purple (Viola)',
    rivals: ['Roma', 'Juventus'],
    schema: { foundingDate: '1926', location: 'Florence, Italy', alternateName: 'La Viola' },
  },
  'atalanta': {
    slug: 'atalanta',
    founded: 1907,
    stadium: 'Gewiss Stadium',
    stadiumCapacity: 24747,
    city: 'Bergamo',
    country: 'Italy',
    nickname: 'La Dea',
    manager: 'Gian Piero Gasperini',
    website: 'https://www.atalanta.it',
    trophies: [{ label: 'Coppa Italia', count: 1 }, { label: 'UEFA Europa League', count: 1 }],
    history: 'Atalanta BC, founded in 1907, have become one of European football\'s greatest stories under Gian Piero Gasperini. Their extraordinary attacking football — averaging over 70 goals per season — has brought Champions League football and a first European trophy, the Europa League in 2024.',
    recentForm: 'Atalanta are one of Serie A\'s most exciting and consistent teams.',
    keyFacts: ['Won the UEFA Europa League in 2024 under Gasperini', 'Averaged over 70 league goals per season under Gasperini', 'From a city of 120,000 — one of Europe\'s greatest football stories', 'Josip Iličić had one of the great individual Champions League performances (4 goals vs Valencia)', 'Consistently sold players at large profits while maintaining quality', 'Gian Piero Gasperini has revolutionised Italian football tactics'],
    colors: 'Blue and Black',
    rivals: ['Brescia', 'Inter Milan'],
    schema: { foundingDate: '1907', location: 'Bergamo, Italy', alternateName: 'La Dea' },
  },
  'torino': {
    slug: 'torino',
    founded: 1906,
    stadium: 'Stadio Olimpico Grande Torino',
    stadiumCapacity: 28177,
    city: 'Turin',
    country: 'Italy',
    nickname: 'Il Toro / Granata',
    manager: 'Paolo Vanoli',
    website: 'https://www.torinofc.it',
    trophies: [{ label: 'Serie A', count: 7 }, { label: 'Coppa Italia', count: 5 }],
    history: 'Torino FC, founded in 1906, have one of Italian football\'s saddest stories. The "Grande Torino" of the 1940s — arguably Italy\'s greatest ever club side — were killed in the Superga air disaster in 1949, claiming 18 players. The club won five consecutive Serie A titles before the disaster. Andrea Belotti, "Il Gallo," recently ended a long association with the club.',
    recentForm: 'Torino are a solid mid-table Serie A side under Paolo Vanoli.',
    keyFacts: ['The "Grande Torino" of the 1940s is considered Italy\'s greatest ever club side', 'The Superga air disaster of 1949 claimed 18 players — one of football\'s greatest tragedies', 'Seven Serie A titles, including five in a row', 'Andrea Belotti scored 113 goals for the club', 'Deep rivalry with Juventus — the Derby della Mole', 'The club had to use Juventus players to complete their remaining fixtures after the disaster'],
    colors: 'Maroon (Granata)',
    rivals: ['Juventus (Derby della Mole)'],
    schema: { foundingDate: '1906', location: 'Turin, Italy', alternateName: 'Il Toro' },
  },
  'bologna': {
    slug: 'bologna',
    founded: 1909,
    stadium: 'Stadio Renato Dall\'Ara',
    stadiumCapacity: 38279,
    city: 'Bologna',
    country: 'Italy',
    nickname: 'I Rossoblu',
    manager: 'Vincenzo Italiano',
    website: 'https://www.bolognafcuk.com',
    trophies: [{ label: 'Serie A', count: 7 }, { label: 'Coppa Italia', count: 2 }],
    history: 'Bologna FC, founded in 1909, won seven Serie A titles between 1925 and 1964 and were a major force in Italian football for decades. After years in Serie A\'s mid-table, Thiago Motta\'s electric management in 2023/24 took them to Champions League qualification for the first time in 60 years — one of Italian football\'s great recent stories.',
    recentForm: 'Bologna are competing in Serie A and European football under Vincenzo Italiano.',
    keyFacts: ['Qualified for the Champions League for the first time in 60 years in 2024', 'Seven Serie A titles (last in 1964)', 'Thiago Motta\'s possession-based style won widespread admiration', 'Joshua Zirkzee was sold to Manchester United for €40m in 2024', 'Riccardo Orsolini is a beloved local hero', 'The Dall\'Ara stadium was built for the 1934 World Cup'],
    colors: 'Red and Blue',
    rivals: ['Fiorentina', 'Parma'],
    schema: { foundingDate: '1909', location: 'Bologna, Italy' },
  },

  // ── LIGUE 1 ──────────────────────────────────────────────────────────────────
  'paris-saint-germain': {
    slug: 'paris-saint-germain',
    founded: 1970,
    stadium: 'Parc des Princes',
    stadiumCapacity: 47929,
    city: 'Paris',
    country: 'France',
    nickname: 'PSG / Les Parisiens',
    manager: 'Luis Enrique',
    website: 'https://www.psg.fr',
    trophies: [{ label: 'Ligue 1', count: 12 }, { label: 'Coupe de France', count: 15 }, { label: 'Coupe de la Ligue', count: 9 }],
    history: 'Paris Saint-Germain, founded in 1970, were transformed by Qatari Sports Investments\' takeover in 2011 into a global superpower. The Neymar (€222m) and Kylian Mbappé signings broke world transfer records. Despite enormous investment, Champions League glory has remained elusive — their only final appearance coming in 2020. Mbappé\'s departure to Real Madrid in 2024 marked the end of an era. Under Luis Enrique, PSG are building a new identity.',
    recentForm: 'PSG are rebuilding their identity under Luis Enrique after Mbappé\'s departure.',
    keyFacts: ['Neymar\'s 2017 transfer (€222m) remains the world record', 'QSI takeover in 2011 transformed the club into a global brand', 'Kylian Mbappé left for Real Madrid in 2024 on a free transfer', 'Champions League finalists in 2020, losing to Bayern Munich', 'Parc des Princes is one of Europe\'s most iconic stadiums', 'Zlatan Ibrahimović spent four trophy-laden years at the club'],
    colors: 'Blue, Red and White',
    rivals: ['Marseille (Le Classique)', 'Lyon'],
    schema: { foundingDate: '1970', location: 'Paris, France', alternateName: 'PSG' },
  },
  'lyon': {
    slug: 'lyon',
    founded: 1950,
    stadium: 'Groupama Stadium',
    stadiumCapacity: 59186,
    city: 'Lyon',
    country: 'France',
    nickname: 'OL / Les Gones',
    website: 'https://www.olympiquelyonnais.com',
    manager: 'Paulo Fonseca',
    trophies: [{ label: 'Ligue 1', count: 7 }, { label: 'Coupe de France', count: 5 }],
    history: 'Olympique Lyonnais, founded in 1950, dominated French football with seven consecutive Ligue 1 titles between 2002 and 2008. Their women\'s team is the most successful in the world, winning the Women\'s Champions League eight times. Jean-Michel Aulas built a remarkable club over his 36-year presidency.',
    recentForm: 'Lyon are rebuilding after financial difficulties.',
    keyFacts: ['Seven consecutive Ligue 1 titles (2002–2008)', 'Women\'s team has won the Champions League 8 times — the most in history', 'Produced Karim Benzema, Alexandre Lacazette and many French internationals', 'The Groupama Stadium opened in 2016 and seats 59,186', 'Jean-Michel Aulas was president for 36 years'],
    colors: 'Blue and White',
    rivals: ['Saint-Étienne (Derby du Rhône)', 'PSG'],
    schema: { foundingDate: '1950', location: 'Lyon, France' },
  },
  'marseille': {
    slug: 'marseille',
    founded: 1899,
    stadium: 'Orange Vélodrome',
    stadiumCapacity: 67394,
    city: 'Marseille',
    country: 'France',
    nickname: 'L\'OM / Les Phocéens',
    manager: 'Roberto De Zerbi',
    website: 'https://www.om.fr',
    trophies: [{ label: 'Ligue 1', count: 9 }, { label: 'UEFA Champions League', count: 1 }, { label: 'Coupe de France', count: 10 }],
    history: 'Olympique de Marseille, founded in 1899, are France\'s only European champions, winning the Champions League in 1993 under Raymond Goethals — a victory later mired in match-fixing scandal. The Vélodrome, one of Europe\'s loudest stadiums, creates an extraordinary atmosphere. Didier Drogba began his career here, and Zinedine Zidane is the most famous player to emerge from their academy.',
    recentForm: 'Marseille are playing exciting football under Roberto De Zerbi.',
    keyFacts: ['France\'s only Champions League winners (1993)', 'The Orange Vélodrome (67,394 capacity) is one of Europe\'s loudest stadiums', 'Roberto De Zerbi joined from Brighton in 2024', 'Zinedine Zidane\'s career began at the Marseille academy', 'The rivalry with PSG (Le Classique) is France\'s most important match', 'Rudi Garcia and Marcelo Bielsa are notable former managers'],
    colors: 'White and Blue',
    rivals: ['PSG (Le Classique)', 'Nice', 'Lyon'],
    schema: { foundingDate: '1899', location: 'Marseille, France', alternateName: 'L\'OM' },
  },
  'nice': {
    slug: 'nice',
    founded: 1904,
    stadium: 'Allianz Riviera',
    stadiumCapacity: 35624,
    city: 'Nice',
    country: 'France',
    nickname: 'Les Aiglons',
    manager: 'Franck Haise',
    website: 'https://www.ogcnice.com',
    trophies: [{ label: 'Ligue 1', count: 4 }, { label: 'Coupe de France', count: 3 }],
    history: 'OGC Nice, founded in 1904, are based on the glamorous Côte d\'Azur and have four Ligue 1 titles. After years as a mid-table club, INEOS\'s takeover in 2019 brought fresh ambition and investment. Situated in one of France\'s most beautiful cities, they regularly compete for European football.',
    recentForm: 'Nice are competing for European places under Franck Haise.',
    keyFacts: ['INEOS (Sir Jim Ratcliffe) takeover brought major investment in 2019', 'The Allianz Riviera looks out towards the Mediterranean', 'Four Ligue 1 titles (last in 1959)', 'Kasper Schmeichel and Jean-Clair Todibo were notable players', 'Based in one of Europe\'s most glamorous cities'],
    colors: 'Red and Black',
    rivals: ['Monaco', 'Marseille'],
    schema: { foundingDate: '1904', location: 'Nice, France', alternateName: 'Les Aiglons' },
  },
  'lille': {
    slug: 'lille',
    founded: 1944,
    stadium: 'Stade Pierre-Mauroy',
    stadiumCapacity: 50186,
    city: 'Lille',
    country: 'France',
    nickname: 'Les Dogues',
    manager: 'Bruno Genesio',
    website: 'https://www.losc.fr',
    trophies: [{ label: 'Ligue 1', count: 4 }, { label: 'Coupe de France', count: 6 }],
    history: 'LOSC Lille, founded in 1944, caused one of Ligue 1\'s greatest upsets by winning the title in 2020/21 under Christophe Galtier, pipping PSG on the final day. Their modern home, the Stade Pierre-Mauroy, opened in 2012. The club are known for excellent player development and selling talent at huge profits.',
    recentForm: 'Lille are competing for European football under Bruno Genesio.',
    keyFacts: ['Won Ligue 1 in 2021, famously pipping PSG on the final day', 'Produced Eden Hazard, Nicolas Pépé and many top talents', 'Stade Pierre-Mauroy is one of France\'s most modern stadiums', 'Champions League knockout stage regulars in recent years', 'Jonathan David is one of Europe\'s most prolific strikers'],
    colors: 'Red and Blue',
    rivals: ['Lens (Derby du Nord)', 'Valenciennes'],
    schema: { foundingDate: '1944', location: 'Lille, France', alternateName: 'Les Dogues' },
  },
  'monaco': {
    slug: 'monaco',
    founded: 1924,
    stadium: 'Stade Louis II',
    stadiumCapacity: 18523,
    city: 'Monaco',
    country: 'Monaco',
    nickname: 'Les Rouges et Blancs',
    manager: 'Adi Hütter',
    website: 'https://www.asmonaco.com',
    trophies: [{ label: 'Ligue 1', count: 8 }, { label: 'Coupe de France', count: 5 }],
    history: 'AS Monaco, founded in 1924, are the only non-French club to play in the top French division. Their 2016/17 team, which won Ligue 1 and reached the Champions League semi-finals, was one of Europe\'s great sides — featuring Kylian Mbappé, Bernardo Silva, Benjamin Mendy and Fabinho, all of whom were sold for enormous profits.',
    recentForm: 'Monaco are competing for Ligue 1 honours under Adi Hütter.',
    keyFacts: ['The 2016/17 squad sold for over €400m — Mbappé, B. Silva, Mendy, Fabinho', 'Champions League semi-finalists in 2017 under Leonardo Jardim', 'Based in the tiny principality of Monaco — a unique club', 'Thierry Henry managed the club in 2018–19', 'Eight Ligue 1 titles', 'The Stade Louis II is one of Europe\'s most charming grounds'],
    colors: 'Red and White',
    rivals: ['Nice', 'Marseille'],
    schema: { foundingDate: '1924', location: 'Monaco', alternateName: 'Les Rouges et Blancs' },
  },
  'rennes': {
    slug: 'rennes',
    founded: 1901,
    stadium: 'Roazhon Park',
    stadiumCapacity: 29778,
    city: 'Rennes',
    country: 'France',
    nickname: 'Les Rouge et Noir',
    manager: 'Jorge Sampaoli',
    website: 'https://www.staderennais.com',
    trophies: [{ label: 'Coupe de France', count: 2 }],
    history: 'Stade Rennais FC, founded in 1901, are Brittany\'s most successful club. Under Julien Stéphan, they qualified for the Champions League group stage for the first time in 2020. The club\'s academy has produced several excellent French players.',
    recentForm: 'Rennes are competing under Jorge Sampaoli.',
    keyFacts: ['Qualified for the Champions League group stage in 2020', 'Brittany\'s biggest club', 'Ousmane Dembélé began his career at Rennes', 'The Roazhon Park has been recently renovated', 'Won the Coupe de France in 1965 and 1971'],
    colors: 'Red and Black',
    rivals: ['Nantes', 'Lorient'],
    schema: { foundingDate: '1901', location: 'Rennes, France' },
  },
  'lens': {
    slug: 'lens',
    founded: 1906,
    stadium: 'Stade Bollaert-Delelis',
    stadiumCapacity: 38223,
    city: 'Lens',
    country: 'France',
    nickname: 'Les Sang et Or',
    manager: 'Will Still',
    website: 'https://www.rclens.fr',
    trophies: [{ label: 'Ligue 1', count: 1 }, { label: 'Coupe de France', count: 1 }],
    history: 'RC Lens, founded in 1906, are the pride of the mining region of northern France. Their passionate "Bollaert" atmosphere is one of French football\'s most famous. After years in lower divisions, they returned to Ligue 1 in 2020 and immediately finished second in 2022/23, qualifying for the Champions League.',
    recentForm: 'Lens are competing in Ligue 1 under Will Still.',
    keyFacts: ['Bollaert-Delelis has one of France\'s most passionate atmospheres', 'Won their only Ligue 1 title in 1998', 'Finished 2nd in Ligue 1 in 2022/23 and played Champions League football', 'Strong mining community roots give the club a unique identity', 'Derby du Nord against Lille is one of France\'s fierest derbies'],
    colors: 'Yellow and Red',
    rivals: ['Lille (Derby du Nord)'],
    schema: { foundingDate: '1906', location: 'Lens, France', alternateName: 'Les Sang et Or' },
  },
  'montpellier': {
    slug: 'montpellier',
    founded: 1974,
    stadium: 'Stade de la Mosson',
    stadiumCapacity: 32900,
    city: 'Montpellier',
    country: 'France',
    nickname: 'La Paillade',
    manager: 'Jean-Louis Gasset',
    website: 'https://www.mhscfoot.com',
    trophies: [{ label: 'Ligue 1', count: 1 }, { label: 'Coupe de France', count: 1 }],
    history: 'Montpellier HSC, founded in 1974, achieved their greatest moment in 2011/12, winning a shock Ligue 1 title under René Girard. Olivier Giroud was their key player before his move to Arsenal. The club is a consistent Ligue 1 presence representing the sunny Languedoc region.',
    recentForm: 'Montpellier are fighting to stay in Ligue 1.',
    keyFacts: ['Won Ligue 1 in 2011/12 — one of France\'s great recent upsets', 'Olivier Giroud was the key player in their title-winning season', 'The club was founded in 1974 — relatively young', 'Based in sunny Montpellier, one of France\'s fastest-growing cities'],
    colors: 'Blue and Orange',
    rivals: ['Nîmes', 'Marseille'],
    schema: { foundingDate: '1974', location: 'Montpellier, France', alternateName: 'La Paillade' },
  },
  'toulouse': {
    slug: 'toulouse',
    founded: 1937,
    stadium: 'Stadium de Toulouse',
    stadiumCapacity: 33150,
    city: 'Toulouse',
    country: 'France',
    nickname: 'Les Violets',
    manager: 'Carles Martínez Novell',
    website: 'https://www.toulouse-fc.com',
    trophies: [{ label: 'Coupe de France', count: 1 }],
    history: 'Toulouse FC, founded in 1937, are nicknamed "Les Violets" for their distinctive purple strip. After years in lower divisions, they returned to Ligue 1 in 2022 and qualified for the Europa League in 2023 — their first European football. The club is connected to RedBird Capital Partners.',
    recentForm: 'Toulouse are establishing themselves back in Ligue 1.',
    keyFacts: ['Qualified for the Europa League for the first time in 2023', 'Connected to RedBird Capital Partners (also own AC Milan and Liverpool stake)', 'Won the Coupe de France in 1957', 'The distinctive purple (violet) strip is one of French football\'s most recognisable', 'The Stadium de Toulouse was a key venue in the 1998 World Cup'],
    colors: 'Purple (Violet)',
    rivals: ['Bordeaux', 'Montpellier'],
    schema: { foundingDate: '1937', location: 'Toulouse, France', alternateName: 'Les Violets' },
  },
}

export function getTeamContent(slug: string): TeamContent | undefined {
  return TEAM_CONTENT[slug]
}
